### ISSUE TITLE
Multiple Drag and Drop

### ISSUE THREAD

**Issue by maloparac** [codef0rmer/angular-dragdrop#114]
I need to make multiple items drag and drop..Where you select item on checkbox and then to move all of them? 

Is it possible to do it with angular-dragdrop?

**Comment by peterhe2000** [comment]
@codef0rmer. Thanks for such a good library. Is it possible to provide example of group multiple items into one container and drag that instead? Thx in advance.

**Comment by codef0rmer** [comment]
@peterhe2000 : I do not have any demo created for now but it will be fairly straight forward. You can make the container as draggable. Try that out and let me know in case you face any problem.

**Comment by boiawang** [comment]
+1

**Comment by JimmyBoh** [comment]
:+1:

@codef0rmer Would it be possible to tap into the directive to just animate the other elements?

**Comment by HMubaireek** [comment]
@codef0rmer 
@Tindtrelle
@peterhe2000 
I've made a working example that supports multi drag&drop using some hack:
http://embed.plnkr.co/lyCnU3gNeGRrTk1D9hh0/

**Comment by codef0rmer** [comment]
@HMubaireek: I do not follow what the plnkr is about? Can you explain?

**Comment by HMubaireek** [comment]
@codef0rmer just some hack to ansewer the question above, multi drag and drop.. after you open the plnker click on any area to get it to focus, then hit ctrl key and select the items you want to drag.

**Comment by codef0rmer** [comment]
I see. It seems sluggish though while dragging.
