### ISSUE TITLE
Published to NPM

### ISSUE THREAD

**Issue by petermelias** [codef0rmer/angular-dragdrop#116]
I noticed this was not published to NPM but it has a package.json file... So I just published it.

I can put in a PR for automating updates and such later but I just wanted to throw that out there in case anyone wonders where that package came from.

**Comment by kcaron-cst** [comment]
It looks like @petermelias is still the owner of this NPM package. What is the status of transferring ownership to @codef0rmer ? 

@petermelias could you publish 1.0.11 in the meantime?

**Comment by eladh** [comment]
Hi . any updates ?

10x :-)

**Comment by petermelias** [comment]
@codef0rmer Hi there. So the only way for me to add you as the owner of the package is to run the following command from my npm account.

`npm owner add codef0rmer`

Then I can remove myself by running `npm owner rm petermelias`

The only problem is you haven't told me your actual NPM username. This is not something that can be solved with a pull request.

As soon as you tell me your NPM username, I will make you the sole owner of the package. I apologize for not being clear enough earlier.

**Comment by codef0rmer** [comment]
@petermelias: It seems my npm username is `codef0rmer` https://www.npmjs.com/~codef0rmer

**Comment by petermelias** [comment]
@codef0rmer She's all yours friend!

@eladh @kcaron-cst resolved.

**Comment by codef0rmer** [comment]
@petermelias: Hehe... Thanks..!
