### ISSUE TITLE
move programmatically a draggable element to a droppable one

### ISSUE THREAD

**Issue by apelliciari** [codef0rmer/angular-dragdrop#127]
Hi,

the project is amazing and it's really simple to enable drag&drop with it.

But i've got in an edge case: my droppable box depends on a select for the number of droppable elements. How can i move the elements in excess from the droppable box to the original list?

An example (pseudo-code):

```
List1 = {elem1, elem2, elem3, elem4}
List2 = {}
Select input with number of elements droppable in List2: 3 elements
```

I drag first three elements from `List1` to `List2` (reaching the maximum droppable elements, the fourth will be invalid).

```
List1 = {elem4}
List1 = {elem1, elem2, elem3}
```

Now I change the select from the value "`3 elements`" to the value "`2 elements`".

So, because my third element is now "invalid", I want to move `elem3` back from `List1` programmatically, without drag&drop.

Can you give me some hint on how to do that?

Thanks,
Alessandro

**Comment by pauloinfotec** [comment]
Hi, 

I'am having same problem.

Can you give some practive example with/without animation?

thanks in advance
