### ISSUE TITLE
How to move each element set css overflow scroll or hidden.

### ISSUE THREAD

**Issue by skywhitefly** [codef0rmer/angular-dragdrop#132]
hi im korean.
i would like to move dragitem from a element to another element
however. your plug-in is can't move each element what have css overflow scroll or hidden.
i have to set css overflow scroll to the element set draggable.

**Comment by jatinseth2007** [comment]
To use it with 'overflow: scroll' solve this issue, we need to use helper: 'clone' with scroll: false option then only it will work
