### ISSUE TITLE
Does not work when compile-time debugging is disabled

### ISSUE THREAD

**Issue by michal-filip** [codef0rmer/angular-dragdrop#137]
Apparently, then compilation-time debugging is disabled in angular (recommended in production), the directives stop working because they rely on a missing function for getting element's scope.

This only causes trouble if this kind of code is used:

```
.config(['$compileProvider', function ($compileProvider) {
        $compileProvider.debugInfoEnabled(false);
    }])
```

See:
https://github.com/codef0rmer/angular-dragdrop/blob/master/src/angular-dragdrop.js#L71
https://github.com/angular/angular.js/issues/9515

**Comment by ha0x7c7** [comment]
this issue is not solved I guess, any solution for it?
