### ISSUE TITLE
`angular-ui-bootstrap-bower` should not be a dependency

### ISSUE THREAD

**Issue by domoritz** [codef0rmer/angular-dragdrop#145]
I think this is used for the demos but it installs some dependencies that are not needed.

**Comment by codef0rmer** [comment]
If I do not add it in bower.json then you can not run the demos locally unless you manually resolve `angular-ui-bootstrap` dependency. Why do you think it's wrong?

**Comment by domoritz** [comment]
I have an app without bootstrap and my build scripts automatically include all bower dependencies (https://github.com/yeoman/generator-angular). This means that bootstrap UI is loaded into my app although it is not needed which breaks some components in the UI. I had to manually delete `angular-ui-bootstrap` from the `package.json` which will of course break if somebody else downloads the code for my app and installs the bower components.

**Comment by mtraynham** [comment]
Broke my build as well, because that particular dependency caused conflicts with the angular version. It uses angular < 1.3 instead of the 1.3.X series.  Make it a dev dependency?

**Comment by codef0rmer** [comment]
@domoritz and @mtraynham guys, let me know if it works for you.

**Comment by mtraynham** [comment]
I would have left the other dependencies in the `dependencies` section as they are requirements for this library.  The `angular-ui-bootstrap-bower` dependency is only for this repo and demo purposes, thus it shouldn't be a requirement for an end-user to install.

**Comment by codef0rmer** [comment]
The `bower install angular-dragdrop` command unnecessarily installs other dependencies in your project under `bower_components/`, now it will not because of `devDependencies`.

**Comment by mtraynham** [comment]
Not sure I follow.  Say I have an empty project and I want my first dependency to be `angular-dragdrop`.  So, I type `bower install angular-dragdrop`.  If I was an ignorant user or used `wiredep`, this would only attach `angular-dragdrop` to the index page.  `angular` nor `jquery` wouldn't be downloaded or attached because you didn't specify them as dependencies.

The `angular-ui-bootstrap-bower` is not a dependency for the end user, it is only a dev-dependency to showcase a running demo.  Follow?

**Comment by codef0rmer** [comment]
Makes sense!

**Comment by domoritz** [comment]
@codef0rmer are you making a new release?

**Comment by codef0rmer** [comment]
@domoritz Yes.

**Comment by domoritz** [comment]
Sweet. I shouldn't be so impatient ;-)

**Comment by codef0rmer** [comment]
@domoritz hehe, done.
