### ISSUE TITLE
Quesion: Is it possible to drag a header which is a group of multiple items?

### ISSUE THREAD

**Issue by peterhe2000** [codef0rmer/angular-dragdrop#148]
Hi. There. Thanks for the effects to make such an excellent angularjs library. 
However, I have got a question for this library. 
This is what i am trying to do.
I got a table like this.
------------------------
Header1    Header2
Item1         Item4
Item2         Item5
Item3         Item6
I want to drag Header1 to a droppable place then item1, item2, item3 are binded to a model variable in the scope.

**Comment by codef0rmer** [comment]
@peterhe2000: If you are using html tables then it's not possible to drag table cells theoretically. I would suggest you to use block level elements such div, ul, li, span, etc. 

If you could share a demo explaining the issue that would be great!
