### ISSUE TITLE
jqyoui-draggable onStart, onStop and onDrag functions start directly on load.

### ISSUE THREAD

**Issue by ferdiemmen** [codef0rmer/angular-dragdrop#149]
When you add a function to the jqyoui-draggable onStart, onStop or onDrag option the function immediately starts running when the page loads.

**Comment by codef0rmer** [comment]
@ferdiemmen: Strange..! I've been using functions in [dnd-frameworks](https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-frameworks.html#L89) demo where it works as expected. Can you share a demo for me to investigate further?

**Comment by ferdiemmen** [comment]
Thank you for your reply. After inspecting your demo's I found out I forgot to quote the functions and that they need to be in the scope.
