### ISSUE TITLE
jQuery UI 'helper' option set to 'clone' still move the content to drop object, instead of copying

### ISSUE THREAD

**Issue by brunomperes** [codef0rmer/angular-dragdrop#150]

**Comment by codef0rmer** [comment]
@brunomperes: Yes, `helper` option is only specific to jQueryUI. If you want to keep the copy of the dragged item where it was already, use `placeholder: 'keep'` option [in the DOM](https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-shoppingcart.html#L53) as:

`<div data-drag="true" jqyoui-draggable="{placeholder: 'keep'}"></div>`
