### ISSUE TITLE
Get dropped item on callback

### ISSUE THREAD

**Issue by lukasstankiewicz** [codef0rmer/angular-dragdrop#151]
Hello,

is it possible to get item dropped in droppable within onDrop callback? I am looking thorugh code and cant find option like this.
 
```
 jqyoui-droppable="{onDrop: 'onDrop'}"  
...
$scope.onDrop = function(event, ui, itemDroped) {}
```

itemDroped is object linked to/copied form draggable ng-model

**Comment by codef0rmer** [comment]
@lukasstankiewicz: Well, you can do it but little differently. I assume you need to access the dragged item which is being dropped in `onDrop` callback. There are two ways to do it:

1. Store drag item on the scope in `onStart` and access it in `onDrop` as [shown here](https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-frameworks.html#L39).
2. You can access the dragged element (DOM) in `onDrop` callback using `ui.draggable`. Then wrap it in `angular.element` to grab it's scope as, `angular.element(ui.draggable).scope()`.

Hope this helps.
