### ISSUE TITLE
how to style an element with 'onOver' ?

### ISSUE THREAD

**Issue by sweather131** [codef0rmer/angular-dragdrop#157]
I have an isolate scope directive that I want to add css style to when hovered over.
my directive:
`
listableresourcegroup(ng-repeat="group in app.currentrssgroupsselection()" grpid="{{ group.id }}" grpname="{{ group.name }}" grpstate="required" getresources="app.getgroupresources(grpid)" hasresources="app.grouphasresources(grpid)" showresources="app.showresources" addtogroup="app.addtogroup(group)" addstyle="app.addhoverstyle()" data-drag="true" jqyoui-draggable="{onStart:'app.setdndresource({rs:group})', onStop:'app.clearlimbo()'}" data-jqyoui-options="{revert: true}")
`
this is the template within my directive:
`
.panel-box-dnd.group(data-drop="true" jqyoui-droppable="{onOver: 'addstyle', onDrop: 'addtogroup({group:group})'}")
`
My onDrop function works great, and passes event,ui and my group object.

However, my onOver function is being called (I have a console.log that fires) but does not pass the event or ui objects. Why?
I planned to style the ui while onOver is called, but this causes a problem.

Is there a better way to style this object when hovered over ?

**Comment by codef0rmer** [comment]
@sweather131: Can you share a demo to better understand the problem?

**Comment by tirli** [comment]
A little correction: you should to use `data-jqyoui-options` not `jqyoui-droppable` attribute. So something like `data-jqyoui-options="{activeClass: 'under-drop'}"`will work

**Comment by codef0rmer** [comment]
@tirli: yeah, thanks..!

**Comment by sweather131** [comment]
thanks @tirli and @codef0rmer . I will close this as I am no longer working on the issue.
