### ISSUE TITLE
How can I return false from beforeDrop?

### ISSUE THREAD

**Issue by Ibrahim-Islam** [codef0rmer/angular-dragdrop#158]
Instead of showing a confirmation I would like to return false immediately and prevent a draggable. How can I do this?

**Comment by codef0rmer** [comment]
Well, `beforeDrop` callback needs to return a promise not a boolean value. So you could probably do is:

```javascript
$scope.beforeDrop = function() {
          var deferred = $q.defer();
          deferred.reject();
          return deferred.promise;
};
```
