### ISSUE TITLE
Is it impossible to use dragdrop with ui.layout directive?

### ISSUE THREAD

**Issue by rom16rus** [codef0rmer/angular-dragdrop#159]
Hi all, thx for attention.
I'm using dragdrop directive with ui.layout (https://github.com/angular-ui/ui-layout). So , i have a problem like this : ui.layout adding new css class - stretch , which has proprery position:absolute and dragdrop works only in div which has class stretch. How can i resolve that problem?

**Comment by codef0rmer** [comment]
@rom16rus: Would you like to share a working demo to understand the problem correctly? Or it might be duplicate of #160
