### ISSUE TITLE
Dropable in iFrame

### ISSUE THREAD

**Issue by IPAOO** [codef0rmer/angular-dragdrop#161]
Hi

Is there a way to make Drag and drop elements into an iframe?

Regards

**Comment by codef0rmer** [comment]
I doubt it will work out of the box but after few searches I came to this demo done in Pure jQueryUI which might be helpful to you.

http://jsfiddle.net/tj_vantoll/kY7FA/

**Comment by petarsubotic** [comment]
Works well with <ng-include>, even if nested.
