### ISSUE TITLE
Swapping items when droppable accept prohibits it

### ISSUE THREAD

**Issue by michaelbrooks** [codef0rmer/angular-dragdrop#165]
When using the `accept` Droppable option, I noticed that draggables which the user cannot otherwise drop onto those droppables will still be swapped into the droppables.

Is there some way to have angular-dragdrop check whether the draggable is accepted by the droppable before it gets swapped into it?

**Comment by codef0rmer** [comment]
You may be looking for https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-lists.html#L43

**Comment by michaelbrooks** [comment]
Well that's cool, I didn't realize you could define data-jqyoui-options with a binding. But I wasn't having trouble getting jQuery UI to recognize the `accept` setting (it refused to drop draggables without the designated class on the drop element).

As far as can tell, it is angular-dragdrop that implements the "swapping" behavior, and I don't see anything in the code that suggests it is checking `accept` before swapping. I guess I should make an example to show what I'm talking about.

**Comment by codef0rmer** [comment]
You can use `beforeDrop` with `jqyoui-droppable`.

http://codef0rmer.github.io/angular-dragdrop/#/confirm

**Comment by michaelbrooks** [comment]
As far as I can observe, `beforeDrop` only gets called for the element that was actually dropped onto, not for the element that is being swapped into.
