### ISSUE TITLE
ngModel creates delay in IE8

### ISSUE THREAD

**Issue by DumboJet** [codef0rmer/angular-dragdrop#168]
Hello.

First of all, thanks for the library.

I have used it on a treeview for dragging and dropping nodes and I have noticed HUGE delays on IE8.
After using an AngularJS plug-in for Chrome to analyze the cause of delays, I have noticed that the largest portion of it was related to a `ngModelWatch`.
I have changed all usages of `ngModel` to `jqyouiModel` and things seemed to be MUCH better in terms of performance.

It seems that the ngModel directive was created as well under the hood and it was doing it's own stuff...
I guess you didn't want that, did you?

So, I suggest going that way in your library, unless you think there's another way.

Thanks! :)

**Comment by codef0rmer** [comment]
@DumboJet: Would you like to share the code?

**Comment by DumboJet** [comment]
My file has many changes in it, so I only send the relevant changes:

I have replaced all :
```
'ng-model'
```
...with:
```
'jqyoui-model'
```
and
```
attrs.ngModel
```
...with:
```
attrs.jqyouiModel
```

To tell you the truth, I do not use ngModel much (I only need the drag-drop functionality).
So, I am not 100% sure if this breaks anything.
But I guess this lib supports no model validation, so I cannot imagine why it would break.

**Comment by DumboJet** [comment]
I have also made this change now:

```
        //scope.$watch(function () { return scope.$eval(attrs.drag); }, updateDraggable);
        //updateDraggable();
        if (attrs.drag !== undefined) scope.$watch(function () { return scope.$eval(attrs.drag); }, updateDraggable);
        updateDraggable(attrs.drag !== undefined ? scope.$eval(attrs.drag) : true);
```
If the `attrs.drag` is not present, there is no need (I think) to use a watcher for it.
I have made it be `true` be default.

**Comment by codef0rmer** [comment]
@DumboJet : Thanks I'll look into this further. BTW, you can enable drag/drop without using ngModel as well, the only difference is that swapping (on drop) will not work out of the box.

**Comment by codef0rmer** [comment]
@DumboJet: I believe `ngModel` is required in case someone makes draggable input elements and might need all the goodies that it provides. So switching to `jqyouiModel` is a bad idea. But the extra watch in `angular-dragdrop` can be avoided if `data-drag` is immutable string.
