### ISSUE TITLE
DragDrop plugin is breaking on my <tr>

### ISSUE THREAD

**Issue by LordWingZero** [codef0rmer/angular-dragdrop#169]
Hello, if you remove the drag and drop tags on the tr the code compiles just fine. But once I add the DD code it stops working.

http://plnkr.co/edit/VerwiEtlUyGXurVwrEaX?p=preview

**Comment by codef0rmer** [comment]
You can only drag block level elements not  `<table>`. So make it block level with `style="display:block;"`
