### ISSUE TITLE
onStop callback function : bindings don't update

### ISSUE THREAD

**Issue by Arnaud49** [codef0rmer/angular-dragdrop#172]
At the end of the onStop callback function, the bindings don't update. To fix it I need to call $scope.$apply() at the end of this function.

You can reproduce this easily by display a counter on the page.

**Comment by codef0rmer** [comment]
To reduce unnecessary digest cycles, I've made the [`$apply` call optional](https://github.com/codef0rmer/angular-dragdrop/commit/6ee1a84eb813b6971428f7081284731acedbed32) since v1.0.9. So you have to call it within the callback if needed.

**Comment by Arnaud49** [comment]
yes but in dropcallback it works ? so for droppable it works but not for draggable. 
It's normal ?

**Comment by codef0rmer** [comment]
Yes, it's called only for dropCallback because I need to swap or update models.
