### ISSUE TITLE
Get drag object on beforeDrop callback

### ISSUE THREAD

**Issue by ihmcjacky** [codef0rmer/angular-dragdrop#173]
I try to get the dragged object and test the drag object before dropping it, how can I obtain it on beforeDrop callback? I can see the 'dndDragItem' after the drop action, but can't get it before the drop, any idea on how to achieve it? Thanks!

**Comment by tmbdrogba** [comment]
You have to do this:

```javascript
$scope.beforeDrop = function(evt, ui) {
    console.log(ui.draggable.scope().dndDragItem);
};
```

**Comment by codef0rmer** [comment]
You can use this as an alternative:
https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-frameworks.html

**Comment by ihmcjacky** [comment]
My appreciation and thanks for the solution, thanks tmbdrogba and codef0rmer
