### ISSUE TITLE
How can i drag an image with animation?

### ISSUE THREAD

**Issue by andreadompe** [codef0rmer/angular-dragdrop#174]
Hi guys,
i have to use this amazing drag & drop library for managing pictures.
I've tried to use an img tag, but for some reason it doesn't have the behavior i expected, i think this is a browser way to treat the image.

Then i'm using a div with a styled background image and if i use ng-src in this 
way ng-src="{{img}}"

the animation doesn't work...  if i set ng-src="myimage.jpg" the animation is ok...

follows my plunker code
http://plnkr.co/edit/ucHkJUtnSEiazObaTO5g

Thanks in advance

Andrea

**Comment by codef0rmer** [comment]
You need an absolute positioning for the image you are dragging.
