### ISSUE TITLE
How to access to dropped element? drop(event, ui) not works in jqyoui-options

### ISSUE THREAD

**Issue by mort3za** [codef0rmer/angular-dragdrop#175]
I just writed this in template:
```html
jqyoui-options="droppableOptions"
```
And in controller:
```javascript
$scope.droppableOptions = {
  drop: function(event, ui){
	console.log('drop ui', ui);
   },
   ...
}
```
But it don't works. Even defining drop function in a scope not works:
```javascript
$scope.dropFunc = function(event, ui){
        console.log('yep');
$scope.droppableOptions = {
  drop: 'dropFunc',
   ...
}
```
Any solution?

**Comment by tmbdrogba** [comment]
The drop callback must be set with the jqyoui-droppable attribute, as a string value of the "onDrop" key:
```javascript
jqyoui-droppable="{onDrop: 'dropCallback'}"
```

And then in your controller:
```javascript
$scope.dropCallback = function (evt, ui) {
   // the model
    var obj = ui.draggable.scope().dndDragItem;
};
```

**Comment by mort3za** [comment]
Thank You So Much! Awesome.

**Comment by mort3za** [comment]
Oh i checked this now, It only returns scope of draggable element! In this scope there isn't any reference to DOM of new clonned element.

**Comment by codef0rmer** [comment]
But you can still store the draggable element in onStop callback and have
it in on onDrop.

**Comment by loverdrive** [comment]
This callback
    $scope.dropCallback = function(evt, ui){
        var obj = ui.draggable.scope().dndDragItem;
    }

dosn't found scope:   Cannot read property 'dndDragItem' of undefined

**Comment by mukumar-qasource** [comment]
@loverdrive did you find a solution for this. I am also doing the same thing 

`$scope.dropCallback = function(evt, ui){
    var obj = ui.draggable.scope();
}`

But ui.draggable.scope() returns undefined. Not sure what I am doing wrong
