### ISSUE TITLE
Does not work on touch devices

### ISSUE THREAD

**Issue by michal-husak** [codef0rmer/angular-dragdrop#177]
even if I include ``angular-touch``

**Comment by michal-husak** [comment]
maybe if you somehow( :) ) include this http://touchpunch.furf.com/ ...

**Comment by michal-husak** [comment]
If you include this library http://touchpunch.furf.com/, it will work. I've tested it.

**Comment by codef0rmer** [comment]
Yeah, angular-touch does not convert all mouse events to touch. So use touchpunch.js.
