### ISSUE TITLE
Drag not working on <tr>

### ISSUE THREAD

**Issue by FrancescoMussi** [codef0rmer/angular-dragdrop#178]
Hello.
I found this issue: i cannot drag an entire row of a table.
I can drag a <td> inside the <tr> without problems, but i need to drag the entire row.

Is this possible?
If not, is possible to look like AS IF is actually dragging the row?
Or is possible to show a custom box while dragging, like when dragging an email inside Hotmail?

Thank you very much

**Comment by codef0rmer** [comment]
You can only drag block level elements. But you can make table element so with `style="display: block;"`
