### ISSUE TITLE
Change img Drag

### ISSUE THREAD

**Issue by izzusan83** [codef0rmer/angular-dragdrop#180]
Hi, is possible to change the drag img?

Code:
img id="test" data-drag="true" jqyoui-draggable="{animate:false, placeholder: 'keep', onStart:'dragCallback(item.order, $index)'}" ng-model="list1" data-jqyoui-options="{revert: 'invalid', helper: 'clone'}" src="img/surgeonGame/icon_forbici.png"

when i start to drag the img, i need to chage this img with another img...

thanks.

**Comment by codef0rmer** [comment]
@izzusan83: You can use [helper](http://api.jqueryui.com/draggable/#option-helper) option and pass a function to mutate the cloned draggable. More info: 
http://api.jqueryui.com/draggable/#option-helper

**Comment by izzusan83** [comment]
hum, is possible to have a example?
because there is just this:
-helper: "clone"

I need to change clone image with a big image.

**Comment by codef0rmer** [comment]
It also takes a function wherein you could modify the dragged image. I do
not have an example with me but you will get plenty on google.

**Comment by izzusan83** [comment]
sorry I misspelled :)

I need to change the clone image...

**Comment by izzusan83** [comment]
I solved,

you need use onStart.

**Comment by codef0rmer** [comment]
@izzusan83: Glad you found a solution..!
