### ISSUE TITLE
drag from a filtered ng-repeat

### ISSUE THREAD

**Issue by wakatanka** [codef0rmer/angular-dragdrop#181]
Hi, i'm making a solution with drag and drop from an ng-repeat list to another, based on the shopping cart example. It works fine until i filter the first list, from when i drag, at that moment the dropped element is not the one i've dragged, but the hidden one. 
You can see an example here:
http://plnkr.co:80/W7KYZlogsj5MKFafdMhC
try to filter the bag list with "zebra" you will have two entry, if you drag "zebra leather" you will have dropped "black leather"

thanks

**Comment by codef0rmer** [comment]
Use `applyFilter` option in jqyoui-draggable as shown in the following example.
https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-filters.html

**Comment by wakatanka** [comment]
No, it doesn't solve, it just order the list, here the updated plunk:
http://plnkr.co/edit/W7KYZlogsj5MKFafdMhC
