### ISSUE TITLE
Module not instantiating Angular 1.4

### ISSUE THREAD

**Issue by jrgleason** [codef0rmer/angular-dragdrop#182]
Seems there is an issue in 1.4. I don't know about other versions but here is a plnkr with the issue

http://plnkr.co/edit/KNe1CGpupDGa4sXNY9Cc?p=preview

    var app = angular.module('plunker', [
      'ngDragDrop'
    ]);
 
    <srcipt src="//codef0rmer.github.io/angular-dragdrop/angular-dragdrop.min.js"></srcipt>

    Uncaught Error: [$injector:modulerr] Failed to instantiate module plunker due to:
    Error: [$injector:modulerr] Failed to instantiate module ngDragDrop due to:
    Error: [$injector:nomod] Module 'ngDragDrop' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by codef0rmer** [comment]
@jrgleason: It seems that github does not serve JS files properly. Save it inline as shown:
http://plnkr.co/edit/WlBOCtcAFSm5GrDU53rX?p=preview

**Comment by jrgleason** [comment]
That doesn't look like the issue, after looking at your sample I copied it over minus my original script src. 

    // Your works
    <script src="//codef0rmer.github.io/angular-dragdrop/angular-dragdrop.min.js"></script>
    // Mine does not
    <srcipt src="//codef0rmer.github.io/angular-dragdrop/angular-dragdrop.min.js"></srcipt>

I can't see any differance but you can try by uncommenting here...

http://plnkr.co/edit/KNe1CGpupDGa4sXNY9Cc?p=preview

Still not sure I can see what the difference is.
