### ISSUE TITLE
Trying to clone an item that isn't in a list is causing the draggable to not drop

### ISSUE THREAD

**Issue by nouellette** [codef0rmer/angular-dragdrop#184]
I'm trying to clone an image and then drop it in the droppable area and continue dropping into that droppable area creating many clones of that image. Seems like it's possible with helper: 'clone' & placeholder: 'keep' but I haven't been able to make this happen, it's probably something silly.

Have a plunker here:
http://plnkr.co/edit/yWcqgwefVD9Kf3Fpj4uI?p=preview

The example shows a button and a single image that are both draggable.
Try dragging them to the dotted container and you will see they don't copy to that droppable area.
Although, if you put a breakpoint on the onDrop function you will see it gets called.

Also, I tried to set clone to 'original' and that allowed it to copy but of course the image will disappear (moved) to the dotted area but when you look at the dom you will notice it technically didn't move.

Can you help me debug the issue here?

I did post a question here if you want to grab some points.
http://stackoverflow.com/questions/30171622/trying-to-clone-an-image-using-angular-dragdrop-but-it-wont-visably-drop

**Comment by nouellette** [comment]
Anyone out there?

**Comment by codef0rmer** [comment]
Answered on SO.
