### ISSUE TITLE
Does this package support touch ? If not can it be put on the feature request list?

### ISSUE THREAD

**Issue by zman13** [codef0rmer/angular-dragdrop#185]

**Comment by codef0rmer** [comment]
Include touchpunch.js before jqueryui.js

**Comment by PeaceS** [comment]
@codef0rmer I think the correct way is to put it 'after' jqueryui.js
I did put it before, and that just make my application always go blank only on touch screen device

**Comment by zman13** [comment]
Thanks!

**Comment by codef0rmer** [comment]
Duplicate of #186
