### ISSUE TITLE
Couldn't drag an item from hierarchy tree into a target container

### ISSUE THREAD

**Issue by JonesXavi** [codef0rmer/angular-dragdrop#191]
Hi,
I use angular-ui-tree for hierarchy, which recursively renders the tree with a template.html . So I gave data-drag for an element inside the recursive template. Now, when I try to drag and drop the item, it gets dragged inside the main container of that hierarchy. Its not coming out to the target DOM. Is there any scope for drag and drop event between the DOM elements? How to solve this? Any help is much appreciable.
Code :
firstpage.html :
Source DOM :
 <div ng-switch-when="fields" class="row-12 auto-scroll bg-white box">
			<div ui-tree data-drag-enabled="false" id="root" >
				<ol ui-tree-nodes ng-model="xmlJson">
					<li ng-repeat="node in xmlJson track by $index" ui-tree-node
					 ng-class="{'selected': models.selected === node}" ng-include="'views/common/recursive_template.html'"></li>
				</ol>
			</div>
		</div>

Target DOM: 
<div data-drop="true" jqyoui-droppable="{placeholder:true,animate:true,onDrop:'dropCallback',onStop:'stopCallback',deepCopy:true}" ui-grid="gridOptions" ui-grid-resize-columns ui-grid-edit
					ui-grid-selection class="row-12 column-12"></div>

recursive_template.html :

<div ui-tree-handle class="tree-node tree-node-content" data-jqyoui-options="{revert: 'invalid'}"  data-drag="true" ng-model="node.key" jqyoui-draggable="{animate:true,deepCopy:true}">
	<div ng-class="(node.value.length > 0) ? 'tree-node-parent-block' : 'tree-node-child-block'">
		<a class="btn btn-tree-node btn-xs"
			ng-if="node.value && node.value.length > 0" data-nodrag
			ng-click="toggle(this)"><span
			ng-class="{
          'fa fa-plus': collapsed,
          'fa fa-minus': !collapsed
        }"></span></a>
		{{node.key}}
	</div>
</div>
<ol ui-tree-nodes ng-model="node.value"  
	ng-class="{hidden: collapsed}">
	<li ng-repeat="node in node.value track by $index" ui-tree-node 
		ng-class="{'selected': models.selected === node}" ng-include="'views/common/tree_renderer.html'"></li>
</ol>

**Comment by codef0rmer** [comment]
If I understand your problem properly, you need to apply `helper:clone` on draggables that will come out of it parent while dragging.

https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-shoppingcart.html

**Comment by JonesXavi** [comment]
Thanks @codef0rmer ! I made some mistake in setting props to jqyoui-droppable. Now its working perfect.
