### ISSUE TITLE
Missing ending semicolon on minified version

### ISSUE THREAD

**Issue by jessicavreeland** [codef0rmer/angular-dragdrop#193]
angular-dragdrop.min.js doesn't have a semicolon at the end of the file which causes errors when it's bundled with other files.

**Comment by Silerra** [comment]
I don't know what system you're working. So I can only say this: Feel free and adds semicolons at the end of the files, if you bundle with other files. :-)

**Comment by codef0rmer** [comment]
@jessicavreeland I think it's there, check the minified version in `src/`.
