### ISSUE TITLE
"TypeError: undefined is not a function" for element.draggable({})

### ISSUE THREAD

**Issue by aqingsao** [codef0rmer/angular-dragdrop#194]
I've included `angular.js`(version 1.4.1) and `angular-dragdrop.js`(version 1.0.11) in my html file, and I use it like the one from the official demo:

`<a class='btn' data-drag="true" data-jqyoui-options="{revert: 'invalid'}" jqyoui-draggable="{animate:true}"></a>`

Thus, I got this error: `TypeError: undefined is not a function`, from source file(angular-dragdrop.js) at line `element.droppable({disabled: true})`;

I don't think it's an issue, but I don't know if I missed something, any help is highly appreciated.

**Comment by codef0rmer** [comment]
Make sure to reference jquery, jqueryUi, and angular in a proper order.
Refer demos in the repos.

**Comment by aqingsao** [comment]
It's what I'm afraid of to reference jQuery...
Would you please update README file and close this issue, and many thanks, codef0rmer.
