### ISSUE TITLE
How to control revert back speed

### ISSUE THREAD

**Issue by phpjagadeesh** [codef0rmer/angular-dragdrop#195]
Hi,
how can we control speed of revert back to original position?

**Comment by codef0rmer** [comment]
You can not. I intentionally made it fast because one might drag the
element which is being animating.

Do you think it should be configurable?

**Comment by qbjagadeesh** [comment]
I think it is possible.

**Comment by Silerra** [comment]
What's about the revertDuration? Doesn't working this option with angular-dragdrop? http://api.jqueryui.com/draggable/#option-revertDuration
I couldn't test this so far.

**Comment by codef0rmer** [comment]
@Silerra You can pass it to `jqyoui-options="{revertDuration: 2000}"` then.
