### ISSUE TITLE
It doesn't even work without ng-model ....

### ISSUE THREAD

**Issue by Burnett01** [codef0rmer/angular-dragdrop#199]
It won't work without ng-model, here is a plunkr: http://embed.plnkr.co/RMD7xWhwTC4AbtMftTgt/preview

As you can see theres no animation, nothing. Thing is I don't want to use lists for my dragable items. They're hardcoded into the template. However it doesn't work somehow.

**Comment by codef0rmer** [comment]
For drag->drop to work, ngModel is mandatory. Although, you can enable dragging without it.

**Comment by Burnett01** [comment]
Ok thanks
