### ISSUE TITLE
Duplicates in repeater are not allowed. 

### ISSUE THREAD

**Issue by beunick** [codef0rmer/angular-dragdrop#200]
Just started to use this drap and drop module. There is an issue I found. When you have the draggable placeholder :'keep' and you tried to drag and drop the same element in the same "drop" field more than once. You have an error:
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: item in list1, Duplicate key: object:10, Duplicate value: {"name":"Package 1","drag":true}

Please advise.
Thanks

**Comment by codef0rmer** [comment]
Use track by $index in ngRepeat.

**Comment by beunick** [comment]
Thanks for the comment.
Well I did not create any ngRepeat. I used your example as it is  in http://codef0rmer.github.io/angular-dragdrop/#/list the only change that I have done is this one: "placeholder:'keep' "
I guess it is one of the directive that you have in your code which maybe need a track by $index.

Do you see what I mean. Maybe you can try to reproduce it, it is easy to reproduce.

**Comment by codef0rmer** [comment]
It's not a bug. When you say "placeholder:keep", it does not remove the
draggable from it's original position after drop. That means there may be a
possibility where you could drop it in the same container - track by is the
solution for such a scenario.

On Thu, Jul 16, 2015 at 10:28 AM, Yannick P. <notifications@github.com>
wrote:

> Thanks for the comment.
> Well I did not create any ngRepeat. I used your example as it is in
> http://codef0rmer.github.io/angular-dragdrop/#/list the only change that
> I have done is this one: "placeholder:'keep' "
> I guess it is one of the directive that you have in your code which maybe
> need a track by $index.
>
> Do you see what I mean. Maybe you can try to reproduce it, it is easy to
> reproduce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codef0rmer/angular-dragdrop/issues/200#issuecomment-121829663>
> .
>



-- 
*With Regards,*
*Amit Gharat*
http://amitgharat.wordpress.com/

*The luckiest person is one whose passion and profession are the same.*

**Comment by beunick** [comment]
Ok bug where do you put 'track by' ? In which ngRepeat ? 
The only ngRepeat is in the droppable container, just by curiosity I put 'Track by' there knowing that it wouldn't change anything.

Please advise.

**Comment by beunick** [comment]
Sorry discard my last comment... track by $index in the ng-repeat of draggable do fix the issue BUT now each bucket "Draggable box" can received the same element more than once which is not what we want... How to prevent the "Draggable Box" to received the same element  more than once when we have "placeholder:keep" ?

Thanks

**Comment by codef0rmer** [comment]
In onDrop callback you can do the validation and revert the dragged
element. Check list example.

**Comment by beunick** [comment]
Ok I will try that. Thank You :)
