### ISSUE TITLE
Pb when draging item "out" of the screen.

### ISSUE THREAD

**Issue by ss-bb** [codef0rmer/angular-dragdrop#204]
Hi. I have a strange comportement (& so you do) when draging an element and going to the right of the page. 

Just as show below, the "container" will move to the left.
Is there a way to stop the system from moving Right if he try to move further than the Screen size?

![rightpb](https://cloud.githubusercontent.com/assets/5887682/9041156/c787d400-3a06-11e5-9347-c3564d9eae27.png)

**Comment by codef0rmer** [comment]
Use [containment](http://api.jqueryui.com/draggable/#option-containment) option in `jqyoui-options="{containment: 'window'}`.
