### ISSUE TITLE
TypeError: element.draggable is not a function

### ISSUE THREAD

**Issue by zeeshanjan82** [codef0rmer/angular-dragdrop#205]
I get the error TypeError: element.draggable is not a function 
I am not sure what am I missing.

**Comment by matejkramny** [comment]
+1

I have jquery.. If Jquery UI is a dependency it should say on the front page, as i wouldn't have installed this in the first place.

**Comment by codef0rmer** [comment]
@matejkramny: Thanks for your suggestion. But it's mentioned jQueryUI drag and drop already - which front page you are referring to?

**Comment by codef0rmer** [comment]
@zeeshanjan82: You have to include jQuery, jQueryUI, and then angular. Please refer examples for more information.

**Comment by matejkramny** [comment]
Sorry I meant readme, and I confused drag and drop with file uploading.

Thanks
On Thu, 6 Aug 2015 at 19:04 codef0rmer <notifications@github.com> wrote:

> @matejkramny <https://github.com/matejkramny>: Thanks for your
> suggestion. But it's mentioned jQueryUI drag and drop already - which front
> page you are referring to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codef0rmer/angular-dragdrop/issues/205#issuecomment-128460575>
> .
>
-- 
Matej Kramny

**Comment by codef0rmer** [comment]
@matejkramny: ohk. Welcome, bro.

**Comment by zeeshanjan82** [comment]
Thanks @codef0rmer
