### ISSUE TITLE
helper as a function not fired

### ISSUE THREAD

**Issue by daniell0gda** [codef0rmer/angular-dragdrop#206]
Hi,
I cannot figure it out, I have
data-jqyoui-options="{ hoverClass: "drop-hover",helper:"getTableDragElement()" }"

and my function isn't fired. Why? Does anybody have working example?

Thanks in advance!

**Comment by codef0rmer** [comment]
@daniell0gda I do not support it yet. But you could rewrite the usage to,

```
$scope.options = {
  hoverClass: "drop-hover",
  helper: $scope.getTableDragElement()
}
```
Then update the template with `data-jqyoui-options="options"`
