### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by matejkramny** [codef0rmer/angular-dragdrop#207]
Hi, just reporting that demo doesn't seem to be working, it appears as a page w/o any styling

**Comment by codef0rmer** [comment]
Which one? demo/* or plunkr ones?

**Comment by matejkramny** [comment]
<img width="1434" alt="screen shot 2015-08-06 at 20 03 18" src="https://cloud.githubusercontent.com/assets/797608/9120782/3d28f0e2-3c76-11e5-85a6-d06cf10c5a2a.png">

It seems only on https:// that it fails due to security

**Comment by matejkramny** [comment]
I get redirects to https: automatically due to an extension *
