### ISSUE TITLE
Access index of dragged element without providing the model or modifying scope

### ISSUE THREAD

**Issue by zaalbarxx** [codef0rmer/angular-dragdrop#208]
Hello!
I'd like to know if there is an option to get access to the index value of element that was dropped without passing ``ng-model`` to both draggable and droppable elements ? I don't want the droppable model to be swapped with the draggable one which is default behaviour here, I just want to drop item into some list element and just know the ids(index) of both drag and drop models so I can take action. As far as I see the ``mutateDraggable()`` method parse the attribute and add it to scope as ``dndDragItem`` but it only fires when both models are passed and that causes an issue for me because of the actions that are made in ``invokeDrop``? Is setting something like ``data-id='{{$index}}'`` and then grabbing it from ``angular.element(ui.draggable).data('id')`` the only way to accomplish this ?

**Comment by codef0rmer** [comment]
Not really but you could access `ui.draggable` in `onDrop` event to access it via `data-index` attribute. But you need to apply the same first.

**Comment by zaalbarxx** [comment]
Ok, I thought there is some built-in option to get the ``index`` from the object that is passed to ``jqyoui-draggable object``. Anyway thanks for the fast answer.

**Comment by nandhacse** [comment]
Not really but you could access ui.draggable in onDrop event to access it via data-index attribute. But you need to apply the same first.



may i know how to do this.. I really don't know how to do this.
