### ISSUE TITLE
Make data-drag="true" on-hold.

### ISSUE THREAD

**Issue by hiteshesfera** [codef0rmer/angular-dragdrop#210]
Hello 

I am working on drag drop application in ionic.

What i am trying to do is change the data-drag="false" to data-drag="true" 
<pre>
<li on-hold="longPressed($event )" on-double-tap="onDoubleTap(item)" data-zone="z1" data-id="{{item.id}}" class="listitem" ng-click="z1ElementClicked(item)" ng-repeat="item in handle.z1level" jqyoui-droppable="{onDrop : 'onDropp(event , ui)'  }" data-drop="true" class="btn btn-primary" data-drag="false" data-jqyoui-options="{helper: 'clone', revert: 'invalid', appendTo: 'body'}"  jqyoui-draggable="{onDrag : 'onDragg(event)' , animate:true}" ><a>{{item.name}}</a>
</li> </pre>

in controller : 

$scope.longPressed = function(event){

console.log($(event.target).parent().data("drag"));
$(event.target).parent().data("drag" , "true");
console.log($(event.target).parent().data("drag"));
}

I am using this code to change the attributes and its working fine but problem is my element is not dragging even after i have changed the attributes is there any way of reloading dom after changing element attribute.?

**Comment by codef0rmer** [comment]
You can use a binding expression in `data-drag="allowDrag"` rather than a string which you could change to true/false in onHold event.

```
$scope.longPressed = function(event){
    $scope.allowDrag = !$scope.allowDrag;
}
```

**Comment by hiteshesfera** [comment]
Hello 
Yes i already tried using this its changing false to true but element is not dragging i think its not reloading element dynamically. any idea?
