### ISSUE TITLE
$.fn.ngattr: $ is undefined

### ISSUE THREAD

**Issue by jllanten** [codef0rmer/angular-dragdrop#214]
Using the latest version 1.0.12 we get this (console) error when loading the plugin. We have jQuery loaded.

Notice that everything works ok Drag and drop is ok, nothing else fails, except that because of this error some other functions/plugins might fail like ng-touch for example. Notice that we are using jQuery 1.9.1 as we are forced to continue using it for some parts of this old, huge application, but it's loaded after angularand it's plugins (so we should be working with the associatd jqLite))

We "fixed" it by using the old version 1.0.11 and we found that i fact this is the piece of code which complains:

angular-dragdrop.js: 410
```javascript
 $.fn.ngattr = function(name, value) {
    var element = this[0];

    return element.getAttribute(name) || element.getAttribute('data-' + name);
  };
```

If the first two lines are replaced by the old version which used prototyping it works:

```javascript
angular.element.prototype.ngattr = function(name, value) {
    var element = angular.element(this).get(0);

    return element.getAttribute(name) || element.getAttribute('data-' + name);
};
```

As a side question, shouldn't we pass angular.element instead of window.jQuery during initialization?

**Comment by codef0rmer** [comment]
I've made [that change](https://github.com/codef0rmer/angular-dragdrop/issues/211) recently to support angular 1.4. More information, https://docs.angularjs.org/api/ng/directive/ngJq and https://github.com/angular/angular.js/issues/12741. Ideally if you are using jQuery (which offcourse mandatory for jQueryUI), `$.fn` should work. 

May I know which angular, jquery, jqueryUI versions are you using?

**Comment by jllanten** [comment]
These are our dependencies:
"jquery": "~2.1.1",    "jquery-ui": "~1.11.0",    "angular": "1.2.x",    "angular-ui-router": "0.2.x",    "angular-bootstrap": "0.11.x",    "angular-loader": "1.2.x",    "angular-mocks": "~1.2.x",    "bootstrap-less": "3.1.x",    "roboto-fontface": "~0.2.4",    "angular-dragdrop": "~1.0.7",    "html5shiv": "~3.7.2",    "respond": "~1.4.2",    "kendo-ui": "~2014.2.716",    "angular-kendo-ui": "~1.0.3", "bower-extjs": "~0.0.4"

The old code which is not bound by these dependencies (we have both new angular,bootstrap,kendo based code and old php, jQuery based code) uses jQuery 2.1.1
      De : codef0rmer <notifications@github.com>
 À : codef0rmer/angular-dragdrop <angular-dragdrop@noreply.github.com> 
Cc : jllanten <jllanten@rocketmail.com> 
 Envoyé le : mercredi 30 Septembre 2015 1h26
 Objet : Re: [angular-dragdrop] $.fn.ngattr: $ is undefined (#214)
   
I've made that change recently to support angular 1.4. More information, https://docs.angularjs.org/api/ng/directive/ngJq and angular/angular.js#12741. Ideally if you are using jQuery (which offcourse mandatory for jQueryUI), $.fn should work. May I know which angular, jquery, jqueryUI versions are you using?—

**Comment by idefy** [comment]
Because this problems creates incompatibility with angular version prior to 1.4 it should be clearly declared as such. The bower.json files  only says latest for angular... so it is not clear how version dependency should be managed. Your bower file needs to be more specific when introducing breaking changes.
Also, it should not be a patch but a minor version change, because it breaks previous functionnality.

If I may recommend something else, it would be good if your library followed somewhat the angular main and minor versions (like ngTouch, etc... do). Not only does it make it cleared, but it also helps in manage angular dependencies with a bower file. So for instance dragdrop 1.0.12 would be 1.4.1 and 1.0.11 would be 1.3.11.

**Comment by codef0rmer** [comment]
I do not think that `$.fn` call would break anyway because jQuery is required. Have a demo?

**Comment by codef0rmer** [comment]
Closing it as it does not look like a bug. Please reopen if the problem persists.

**Comment by tomasz-szymanek** [comment]
Problem persists.
