### ISSUE TITLE
An additional attribute is being added to the JSON on using insertInline option 

### ISSUE THREAD

**Issue by suryateja619** [codef0rmer/angular-dragdrop#215]
Hi,
I was trying to use drag and drop module to drag the items and as well sort them in the list. When I included an option for enabling sorting to my list using (insertInline = "true") to my div element. The functionality was working fine, but there is an additional attribute which is being added to the JSON. I believe it is adding a direction property. How to avoid it being appended to my JSON data?

Here is the working example: http://plnkr.co/edit/FdhZNgm4vNsCXNxdsuAg?p=preview

**Comment by codef0rmer** [comment]
For sortable to work, separate droppables are required for each draggable. Refer, https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-insertInline.html

**Comment by suryateja619** [comment]
Well I could able to implement the sortable to work. But when I am using (insertLine) attribute there an additional element which is being append to the JSON(http://plnkr.co/edit/gkvcFs?p=preview). The above plunker is exactly the one from the sortable example. 

I just made a change to display the JSON in the above plunker and if you sort the list you can observe that there is an additional ("jqyouiDirection": "right") is being appended to the JSON.

**Comment by codef0rmer** [comment]
That's necessary for animation used internally by angular-dragdrop. Any problem?

**Comment by suryateja619** [comment]
Well, I need to save the JSON data and would like to remove it before saving.

**Comment by codef0rmer** [comment]
Oh, then I need to think about getting rid of it without affecting ngAnimation.
