### ISSUE TITLE
Ho do I get the item on 'onStart' / 'onDrop' events? 

### ISSUE THREAD

**Issue by DvirH** [codef0rmer/angular-dragdrop#216]
When I'm trying to get the angular item I just getting the event and the jquery object of the element.
Ho do I get the angular item in the model so i can see his properties?

**Comment by simonghales** [comment]
Hey @DvirH I'm guessing you closed this because you found out the solution? Do you mind sharing?

**Comment by codef0rmer** [comment]
@simonghales: It's `onStart = function(event, ui) { console.log(ui.draggable.scope()); }`

**Comment by simonghales** [comment]
@codef0rmer Thank you, and thanks for the terrific plug in.
