### ISSUE TITLE
Error: [ngRepeat:dupes] when I use sortable and drag & drop functionality

### ISSUE THREAD

**Issue by suryateja619** [codef0rmer/angular-dragdrop#217]
Hi, 

I am getting a duplicates in a repeater error message when I am trying to use both sortable and drag & drop functionality being implemented at the same time.

Error: [ngRepeat:dupes] http://errors.angularjs.org/1.2.8/ngRepeat/dupes?p0=item%20in%20selectedFilters&p1=object%3A00N
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:6:449
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:184:445
    at Object.fn (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:99:371)
    at h.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:100:299)
    at h.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:103:100)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:113:146
    at e (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:33:287)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.8/angular.min.js:37:1

I was using {index: {{$index}} for jqyoui-droppable and  jqyoui-draggable. Here is the working demo :  http://plnkr.co/edit/L5VvBU8S9IOff068AfM1?p=preview

Any thoughts?

**Comment by codef0rmer** [comment]
Try using `track by` with ngRepeat.

**Comment by suryateja619** [comment]
I tried it in ngRepeat and there is another interesting issue with using 'track by' is that the draggable events are being duplicated. For instance, let us consider two lists List1(A) and List2(B). If A is being dropped in List2 then both the items in the List2 are 'B' & 'B' instead of  'A' & 'B'.

**Comment by codef0rmer** [comment]
Can you share a  demo?

**Comment by suryateja619** [comment]
Here is the working demo http://plnkr.co/edit/foQADRtR7aGqFmIz182B?p=preview

**Comment by codef0rmer** [comment]
@suryateja619: That's because angular animate waits for 10ms by default before it applies ng-leave/ng-enter classes on elements being rearranged unless you overwrite the default time in css. So two options you can go with:

1. Add 0ms transition on animating divs
```
.containerVertical div.ng-leave {
  -webkit-transition-duration: 0s;
  transition-duration: 0s;
}
```
2. Get rid of `ngAnimate` module dependency if you do not need it.
```
var App = angular.module('drag-and-drop', [/*'ngAnimate', */'ngDragDrop']);
```

**Updated demo:** http://plnkr.co/edit/lZKi9i?p=preview
