### ISSUE TITLE
Draggables go behind elements when they are custom angular js element directives (chrome only)

### ISSUE THREAD

**Issue by therocode** [codef0rmer/angular-dragdrop#219]
Hello!

I was struggling to solve this problem of mine where draggables would go behind other elements that come after it in the DOM tree. After a lot of fiddling, I managed to create this JSfiddle which reproduces this issue: https://jsfiddle.net/1phycjjx/1/

In it I have created some 'tasks' which are all draggables. All of them are created using a custom <task> directive, except for one (the yellow one). If you drag them around, you'll notice that they go behind all tasks below itself, but not above itself. Furthermore, tasks on the left even go behind normal <div> with <p> in them on the right side. If the draggable task which is not created using the <task> directive but just a hard coded <div> is dragged, it works as expected where the dragged task is above everything else.

This is only apparent in chrome btw.

I am not sure if this is a bug, or if it is a bug, that it is from angular-dragdrop, but maybe you'll be able to tell. Also, any help on how to make this work as expected is very welcome. Thanks!

**Comment by codef0rmer** [comment]
Did you try setting `z-index` to the draggable in onStart event and remove it once dropped.

**Comment by therocode** [comment]
Yes, I did. That seemingly has no effect at all on the issue.

**Comment by wetternest** [comment]
same problem here, z-index on the draggable is set
the problem can be fixed by adding z-index to the parent of the draggable - weird

**Comment by phsstory** [comment]
@codef0rmer  this wrapper seems to override the zIndex option of jQueryUI draggable

https://github.com/codef0rmer/angular-dragdrop/blob/master/src/angular-dragdrop.js#L205
https://github.com/codef0rmer/angular-dragdrop/blob/master/src/angular-dragdrop.js#L315

I have removed these references to z-index and used the underlying zIndex option
http://api.jqueryui.com/draggable/#option-zIndex
which brought this wrappers drag behavior inline with the behavior from pure jQuery solution.

**Comment by codef0rmer** [comment]
@phsstory: How did you fix the problem?

**Comment by phsstory** [comment]
```
205c205
<       $fromEl.css({'position': 'absolute', 'z-index': 9999})
---
>       $fromEl.css({'position': 'absolute'})
315c315
<                   $(jqyouiOptions.helper ? ui.helper : this).css('z-index', 9999);
---
>                   //$(jqyouiOptions.helper ? ui.helper : this).css('z-index', 9999);
```
and the native
```
data-jqyoui-options="{accept:'.role',activeClass:'droppable-target',hoverClass:'droppable-hover',opacity:0.7,helper:'clone',zIndex:10000000,handle:'.panel-heading'}"
```

I can't remember why we needed such a high z-index, but I believe it had to do something with a *this shall always be on top* edict from bootstrap that we needed under an occlusion layer

**Comment by codef0rmer** [comment]
For me, adding `10000000` zIndex is not moving the draggable above all. Did it work for you?

**Comment by phsstory** [comment]
yes, the posted solution works for us based on the [a03e12da697e6267ef2680b8d2b6082b43a78475](https://github.com/codef0rmer/angular-dragdrop/tree/a03e12da697e6267ef2680b8d2b6082b43a78475) version

**Comment by codef0rmer** [comment]
@phsstory: Sorry I do not follow. Can you create a working demo?
