### ISSUE TITLE
Im having issues with $index/index

### ISSUE THREAD

**Issue by zoesteinkamp** [codef0rmer/angular-dragdrop#220]
So from what i was hoping/understood index should return the actual $index from the array. So my model has a list of 5 items all with indexes, but when when i run this line.
  $scope.onDrop = function($index){console.log($index)}

I get this when i console log this is what i get back, but there is no actual index, like 1,2,3, etc...

[Log] Object (PhotoplanFloorplanCtrl-b60ba29d101044bbde33244ef25aa3d6.js, line 20)
altKey: false
bubbles: true
button: 0
buttons: undefined
cancelable: true
clientX: 573
clientY: 301
ctrlKey: false
currentTarget: #document {embeds: HTMLCollection [], plugins: HTMLCollection [], scripts: HTMLCollection, all: HTMLAllCollection, …}
data: null
delegateTarget: #document {embeds: HTMLCollection [], plugins: HTMLCollection [], scripts: HTMLCollection, all: HTMLAllCollection, …}
eventPhase: 3
fromElement: null
handleObj: {type: "mouseup", origType: "mouseup", data: null, handler: function, guid: 420, …}
isDefaultPrevented: function()
isTrigger: 3
jQuery111304540524990297854: true
metaKey: false
namespace: ""
namespace_re: null
offsetX: 21
offsetY: 14
originalEvent: {originalEvent: MouseEvent, type: "mouseup", isDefaultPrevented: function, timeStamp: 1444848967265, jQuery111304540524990297854: true, …}
pageX: 573
pageY: 510
relatedTarget: null
result: undefined
screenX: 600
screenY: 363
shiftKey: false
target: img.ng-scope.ui-droppable {jQuery111304540524990297854: 313, name: "", align: "", alt: "", border: "", …}
timeStamp: 1444848967265
toElement: img {name: "", align: "", alt: "", border: "", crossOrigin: "", …}
type: "drop"
view: Window {undefined: undefined, window: Window, NaN: NaN, dialogModule: Object, document: #document, …}
which: 1
Object Prototype

Am i missing something here? I have tried everything from id, to item.id to item.index. Im being driven up a wall trying to figure out this problem. Does index just not actually return the index? And if so how can i get the index? I have two ng-repeats, and i need some kind of identifier for these. 

Any help is really appreciated, thank you. Im also willing to send more code if needed.

**Comment by codef0rmer** [comment]
Yeah, because the first two arguments are `event` and `ui` so the index will be available in the third parameter.

`$scope.onDrop = function(event, ui, $index){console.log($index)}`
