### ISSUE TITLE
Dynamic binding of data-drop and data-drag when using a template

### ISSUE THREAD

**Issue by istvanpuskas** [codef0rmer/angular-dragdrop#222]
As far as a know dynamically settings those attributes in the markup (such as data-drag={{dragEnabled}}) should work, however if I put this binding in the template markup, it does not work. Is there a way to workaround this?

**Comment by codef0rmer** [comment]
I believe it has to be a string (true/false) or a model with boolean value. Interpolation such as `data-drag="{{drag}}"` may not work because I do not support it for now.

https://github.com/codef0rmer/angular-dragdrop/blob/master/src/angular-dragdrop.js#L400
