### ISSUE TITLE
Issue with Drag and Drop Swapping When Not Desired

### ISSUE THREAD

**Issue by davidmillercode** [codef0rmer/angular-dragdrop#223]
I've been playing around with this for awhile, but I'm not quite sure what the issue is here?  I'm using dragdrop 1.0.11 w/ angular 1.4.3.  I would like the dropped divs to not swap (if I take the last element and put it 1st, I would like the original first element to now be 2nd).  I would appreciate any help and here's the code I have that won't work: 

```html
<div class="btn btn-droppable" ng-repeat="item in classifier.categories" 
data-drop="true" ng-model='classifier.categories' jqyoui-droppable="{index: {{$index}}}">
            <div class="btn btn-info btn-draggable" data-drag="true" data-jqyoui-options="{revert: 'invalid'}" ng-model="classifier.categories" jqyoui-draggable="{animate:true, index: {{$index}}}"
                 ng-keyup="$event.keyCode == 8 ? deleteFromClassifierStatement(classifier.categories, $index) : null"
                 ng-class="{greenify: item.other}">{{item.name}}
            </div>
</div>

**Comment by davidmillercode** [comment]
Any ideas?  I am using angular-material in other parts of this project, which may be interfering.

**Comment by codef0rmer** [comment]
@davidmillercode : Demo?
