### ISSUE TITLE
Bind of jqyouiOptions 

### ISSUE THREAD

**Issue by arcadeJHS** [codef0rmer/angular-dragdrop#224]
Is it possible to bind the jqyouiOptions in a way that when the options are updated (for instance, grid definition) they are reflected into the directive?

**Comment by codef0rmer** [comment]
I think you can use binding expression as `data-jqyoui-options="{{optionsList1}}"`.

**Comment by arcadeJHS** [comment]
It doesn't seem to work.
Maybe it also require a wather on "jqyouiOptions" to call updateDraggable?
But it triggers an infinite digest.
