### ISSUE TITLE
drag item not fitting exactly to droppable

### ISSUE THREAD

**Issue by alaksandarjesus** [codef0rmer/angular-dragdrop#228]
Hi

I was trying  this plugin for one of my project where the drop area is more than 100px. My drag area and drop area were both of same size.

Now if i drag the item to the droppable, and if the draggable center and droppabe middle matches, it stops at that point. I need the draggable to fix exactly to the center. How can i achieve that?

Here with i am attaching the snapshot of your demo for further information.

**Comment by codef0rmer** [comment]
Duplicate of #229
