### ISSUE TITLE
drag item not fitting exactly to droppable

### ISSUE THREAD

**Issue by alaksandarjesus** [codef0rmer/angular-dragdrop#229]
Hi

I was trying  this plugin for one of my project where the drop area is more than 100px. My drag area and drop area were both of same size.

Now if i drag the item to the droppable, and if the draggable center and droppabe middle matches, it stops at that point. I need the draggable to fix exactly to the center. How can i achieve that?

Here with i am attaching the snapshot of your demo for further information.
![2015-11-08 20_14_41-drag and drop for angularjs](https://cloud.githubusercontent.com/assets/4712552/11020908/d97879f8-8655-11e5-8920-2f615fd401d2.png)

**Comment by codef0rmer** [comment]
Would you mind sharing a demo link?

**Comment by alaksandarjesus** [comment]
I was trying to create a demo in jsfiddle but couldnt map the angular-drag and drop.js file. Here is the working codes of the demo

https://jsfiddle.net/Lkq6duor/1/

**Comment by codef0rmer** [comment]
@alaksandarjesus: Demo does not work?

**Comment by alaksandarjesus** [comment]
I have created a exact copy of your plunker demo filter with drag and drop. You can see the animation working in yours but not in mine. Kindly let me know what is that i am missing out.

http://plnkr.co/edit/g92u9ccrnWK1qfwdiJ2P?p=preview

**Comment by codef0rmer** [comment]
@alaksandarjesus: You had applied `applyFilter: 'filterIt'` on draggables but never defined `filterIt` function in the controller.

http://plnkr.co/edit/KaO4j5hn0de5SBgXE3eQ?p=preview
