### ISSUE TITLE
Input keep focus while start dragging

### ISSUE THREAD

**Issue by giladk** [codef0rmer/angular-dragdrop#230]
Hi.
As you can see in this demo : 
http://plnkr.co/edit/snMB5TRNwj2QZ9UJU568?p=preview
which using angular 1.3 + ng-model-options="{updateOn: 'blur'}"
Because input is not being blur when start dragging , the model in not updated.
Anyway, I don't know if this should be the default behavior or not , but maybe it should be an option?

I solved this by adding this row to angular-dragdrop.js - line 313 - start-drag method
if (document.activeElement != document.body) document.activeElement.blur();

Working example :
http://plnkr.co/edit/MkbR6FQUkHfCAHqks4OQ?p=preview

Thanks in advance,
Gilad.

**Comment by codef0rmer** [comment]
@giladk: you could write the same patch in `onStart` callback as shown in the below example.
http://plnkr.co/edit/b03bHgO8dyJhLAyKJ1Do?p=preview

**Comment by giladk** [comment]
@codef0rmer 
Hi, thank for that, but it's not seems like good practice to write this : 
if (document.activeElement != document.body) document.activeElement.blur();
inside controller.

Can i add pull request that use an new draggable option? something like : blurFocusedInput

With option the user can also set this as default behavior.

Thanks.

**Comment by codef0rmer** [comment]
@giladk It does not make sense to add more option to do just that because the callback method `onStart` is just a JS function (though it's bound to $scope) that does not trigger digest loop by default. So it's okay to use as I suggested.

**Comment by giladk** [comment]
@codef0rmer  
Sure it's okay and will work , but generally it's a good practice to void DOM manipulations inside controllers, so -  if (document.activeElement != document.body) document.activeElement.blur() should not be there.
That why i think it's better to be in the directive.
Anyway, thanks for the response and for the great package.

**Comment by codef0rmer** [comment]
It's not recommended to have DOM manipulation code inside controller based on the assumption that the scoped method might be evaluated many times. However, in our case it's not. I've seen ui-bootstrap doing DOM manipulation in services :-)
