### ISSUE TITLE
Sortable not graceful if dragged out of boundaries and in-between sorting.

### ISSUE THREAD

**Issue by NenadP** [codef0rmer/angular-dragdrop#231]
I implemented horizontal sortable list, but if I try to drag item beyond the first/last position, it does not assume my intention and does not apply  (I see same is happening for the vertical demo one).

Also, some in-between sorting attempts does not apply intuitively, If yo drag an item too much above the desired item where you want to drop, it does not apply.

Is there a way to tweak sensitivity of sortables to address those issues?

**Comment by codef0rmer** [comment]
@NenadP Would you share a demo?

**Comment by codef0rmer** [comment]
@NenadP The `tolerance` option in `jqyoui-options` might be helpful.

http://api.jqueryui.com/droppable/#option-tolerance
