### ISSUE TITLE
Animate when beforeDrop results in rejection

### ISSUE THREAD

**Issue by galeano** [codef0rmer/angular-dragdrop#233]
I'm using 'beforeDrop' to validate some custom data before allowing a draggable to be dropped. When the validation is rejected, the draggable snaps back up to its original position without animation.

I've enabled 'animate' for cases when the draggable element is dropped in a random zone (not a droppable) and that works fine. So it's just for the case of a rejected 'beforeDrop'.

Is this possible today?

Thank you for your great work.

**Comment by codef0rmer** [comment]
@galeano: Yeah in that case I simply remove zIndex, left, and top properties which is what snaps the draggable to it's original position. Would you mind sending a PR with `animate` call at https://github.com/codef0rmer/angular-dragdrop/blob/master/src/angular-dragdrop.js#L276

**Comment by galeano** [comment]
@codef0rmer Sure thing, I'll send it later this weekend. Thanks!

**Comment by NickBertrand** [comment]
I'm trying to get this animate to work, but I am not having any luck. My code is doing what it's supposed to it's just the animate. Any Ideas? 

HTML:
`<div id = "{{room.number}}" class="room" data-drop="true" data-jqyoui-options ng-model="room[room.number]" jqyoui-droppable="{multiple:true, onDrop:'dropCallback', beforeDrop: 'beforeDropCallback'}" jqyoui-options="{revertDuration: 10000}">{{room.number}}
                <div data-drag="true" data-jqyoui-options="{revert: 'invalid', helper:'clone'}" ng-model="room[room.number]" jqyoui-draggable="{index: {{$index}}, placeholder: 'false', onStart:'startCallback(room[room.number], $index)'}">{{room[room.number].name}}</div>
            </div>`

JS: 

     $scope.beforeDropCallback = function() {
      var roomSize = Object.size($scope.rooms[this.$index]);
      var deferred = $q.defer();

      if(roomSize >= 3){ //Size with 1 person in there equals 3;
        deferred.reject();
      }else{
        deferred.resolve();
      }
      return deferred.promise;

    };

**Comment by codef0rmer** [comment]
@NickBertrand Can you share a demo?

**Comment by NickBertrand** [comment]
This is close enough: 

I have your example which is working so I'm guessing it must be something to do with the ng-repeat? 

To use: Drag one of the button names onto one of the black squares. If there is someone already in it, it does not place that person in it, and it needs to animate back to the list like if you drag it not in one of the black squares. 

http://plnkr.co/edit/IkJpnn8JvpvctXDnO0CA?p=preview

Thanks for the help! Love this wrapper! Thanks so much!

**Comment by codef0rmer** [comment]
@NickBertrand You can not define the same controller multiple times, try using the same controller for both sections. Also spend some time to start small - instead of rendering complex data, try with single item to bring the desired effect. Let me know if stuck :-)

**Comment by NickBertrand** [comment]
Ah I found it. You helped me pinpoint it. I thought it was having trouble with the droppable boxes, but it was actually the draggable item! It's having trouble with the data-jqyoui-options{helper:'clone'}. For some reason that breaks it and disabling it fixes it. 

(And although in my app there's only one controller over both sections (at the very top), I didn't know about defining it multiple times. It's good to know. Thanks!) 

Plunker: http://plnkr.co/edit/IkJpnn8JvpvctXDnO0CA?p=preview
