### ISSUE TITLE
NPM version is way behind

### ISSUE THREAD

**Issue by galeano** [codef0rmer/angular-dragdrop#234]
The current version in NPM is 1.0.5 (https://www.npmjs.com/package/angular-dragdrop), the one on the repo here is 1.0.12, which is the one I'm using in my code.

'beforeDrop' doesn't work on 1.0.5 so my app is not working on my remote environment. Hope we can get an update on NPM soon. Thanks!

**Comment by petermelias** [comment]
#116

**Comment by codef0rmer** [comment]
@galeano Done.
