### ISSUE TITLE
sound effect on drag?

### ISSUE THREAD

**Issue by vrohitk** [codef0rmer/angular-dragdrop#237]
How do i add a mp3 or wav sound effect on drag

**Comment by codef0rmer** [comment]
@vrohitk: have couple of buttons hidden in the page that can play/pause audios. On drag/drop, trigger any button click to play the audio in `onDrag` or `onDrop` events. Follow examples for more info.

**Comment by vrohitk** [comment]
@codef0rmer thank you, will try that

**Comment by codef0rmer** [comment]
@vrohitk: Reopen in case of any help.
