### ISSUE TITLE
Drag item from list to grid?

### ISSUE THREAD

**Issue by cquillen2003** [codef0rmer/angular-dragdrop#239]
I'm trying to build a sortable list of items that can be dragged and dropped into specific slots on a calendar grid/table. Is this possible with angular-dragdrop?

Is the "Snap to element or grid" functionality from jQuery UI Draggable available?

Thank you!

**Comment by codef0rmer** [comment]
You can used all jQueryUI options in angular-dragdrop in `jqyoui-options` directive. Take a look at some of the examples.

**Comment by cquillen2003** [comment]
Great, thank you!
