### ISSUE TITLE
Sortable example?

### ISSUE THREAD

**Issue by cquillen2003** [codef0rmer/angular-dragdrop#240]
I cannot get a simple sortable list (vertical) working.

Can you please provide an example of a normal (vertical) list that is sortable?  The demo example is horizontal items.  Most use cases for sortable lists are vertical.  Please provide a simple example if possible.

**Comment by codef0rmer** [comment]
@cquillen2003: check this out: http://codef0rmer.github.io/angular-dragdrop/#/sortable
