### ISSUE TITLE
Different behavior between angular versions

### ISSUE THREAD

**Issue by arn80** [codef0rmer/angular-dragdrop#241]
Hi
On the demo site with the simple example, Angular 1.0.4 is used:
http://codef0rmer.github.io/angular-dragdrop/#/

The draggable element stays where it was dropped in the droppable area.

The behavior is different, when I use newer Angular versions like 1.4.8.
Then the dropped element snaps to the droppable area.

Example with Angular 1.0.4:
https://jsfiddle.net/dres/0ob34u97/

Example with Angular 1.4.8:
https://jsfiddle.net/dres/wt6wn2z7/

How do I get the same behavior form Angular 1.0.4, when I am using newer Angular versions?

Thank you!

**Comment by codef0rmer** [comment]
@arn80: Thanks for letting me know. It seems that angular version prior to 1.2.0 never resolves the promise (https://github.com/codef0rmer/angular-dragdrop/blob/master/src/angular-dragdrop.js#L382) by default. You have to call `$apply` or `$timeout` to do so. 

That means the behavior with v1.0.4 is wrong, it should animate inside the droppable area like in v1.4.8. I'll add a fix soon.

**Comment by codef0rmer** [comment]
@arn80: I'll recommend using angular v1.2+ rather than fixing angular-dragdrop for v1.0.4.

If you do not want it to animate after drop, simply remove ng-model on the droppable (prevent swapping models) but I doubt that you expecting that.
