### ISSUE TITLE
How do i remove dropped item?

### ISSUE THREAD

**Issue by rohitkumarvinay** [codef0rmer/angular-dragdrop#244]
I would like to have a remove button, on-click the dropped item should be removed.

**Comment by codef0rmer** [comment]
That can be done easily. I hope you know how to add a remove icon on top-right corner of the draggable item. Once that's added, you can simply splice the collection/array based on the item index and ngRepeat will automatically remove the associated DOM.

**Comment by rohitkumarvinay** [comment]
Thank you worked like a charm `<div ng-repeat="option in options" ng-init=options=[1,2,3,4,5]>
   <button ng-click="options.splice($index,1)">Remove me</button>      
</div>`
