### ISSUE TITLE
$index undefined

### ISSUE THREAD

**Issue by getglad** [codef0rmer/angular-dragdrop#246]
I am using the clone option to create an 'options' list to generate a 'target' list (ie, you could have options of A,B,C,D,E and make a list of A, A, D, C, C, E). I am able to drag and drop fine on the UI end. My DOM looks like the below:

Options List:

    <a data-drop="true" ng-repeat="item in list5 track by $index" ng-model="list5" data-jqyoui-options="{accept:'.btn-draggable:not([ng-model=list5])'}"  jqyoui-droppable="{index: {{$index}}}">
     <div class="btn btn-info btn-draggable" data-drag="{{item.drag}}" data-jqyoui-options="{revert: 'invalid', helper: 'clone'}" ng-model="list5" jqyoui-draggable="{index: {{$index}}, placeholder:'keep', animate:true}" ng-hide="!item.title">
       ...content...
     </div>
    </a>

Target List:

    <div data-drop="true" ng-repeat="item in list1 track by $index" ng-model="list1" data-jqyoui-options="{accept:'.btn-draggable:not([ng-model=list1])'}" jqyoui-droppable="{multiple:true, onDrop:'onDrop'}">
      <div class="btn btn-info btn-draggable" data-drag="{{item.drag}}" data-jqyoui-options="{revert: 'invalid'}" ng-model="list1" jqyoui-draggable="{index: {{$index}},animate:true}" ng-show="item.title" >
        ...content...
      </div>
    </div>

On the controller side of things, though, my $index is undefined when I drop an item:

    $scope.onDrop = function(event, ui, $index) {
      console.log(event); //defined
      console.log(ui); //defined
      console.log($index); //undefined
    }

Also if I were to include `index: {{$index}}}` on my target's `jqyoui-droppable`, it will only hold 1 item in the array - each drop overwrites the existing first position.

I'm sure there is something I'm not catching here, but I'm not sure what it is. Any obvious issues with my setup here?

**Comment by codef0rmer** [comment]
It seems that `$index` on onDrop will not pass the draggable's index. You should store the `$index` passed to `onStart` and use it in `onDrop` instead. 

If you share a demo, I'll be more easily to find the issue.

**Comment by getglad** [comment]
Thanks for taking a look - let me play around with that and I'll get a demo up.
