### ISSUE TITLE
c.draggable issue when add jqyoui-draggable

### ISSUE THREAD

**Issue by Davids89** [codef0rmer/angular-dragdrop#248]
Hello, I have an error when I use jqyoui-draggable in my div. I'm following the web example so I don't modify anything. What can It be?

**Comment by poshest** [comment]
What is the error?  You have to give more details or it's impossible to help you

**Comment by Davids89** [comment]
It says that c.draggable is not a function.

**Comment by Davids89** [comment]
![pete](https://cloud.githubusercontent.com/assets/7094136/12016819/ee0b019e-ad4f-11e5-9357-2db225836eed.PNG)

**Comment by codef0rmer** [comment]
It seems that the jquery and jquery-ui are not added in the proper order. Can you create a demo?

**Comment by Davids89** [comment]
Ok. I installed jquery-ui and now I can drag the item. Thanks!

**Comment by khullah** [comment]
Same here.
Oh no, I have to install jquery-ui? Can't do that in my project.

**Comment by codef0rmer** [comment]
@khullah Use https://github.com/bevacqua/dragula instead.

**Comment by khullah** [comment]
Thanks @codef0rmer!
