### ISSUE TITLE
How to edit a cloned object with jQuery

### ISSUE THREAD

**Issue by Davids89** [codef0rmer/angular-dragdrop#249]
Hello! I'm cloning objects to drag it to other side of the web, but my problem is that I'm using a directive to create this objects. When I dragged it, I need to change the class of this cloned, but in jQuery there is a reference that change the class in both.

How can I select the cloned object? Is there any internal function for it?

**Comment by codef0rmer** [comment]
If I understood your issue correctly, you want to select the cloned element and apply some styling to it. If so, every event in angular-dragdrop such as `onStart` gives access to `ui` object. Use `ui.helper` to grab the cloned element.

More Info: http://api.jqueryui.com/draggable/

**Comment by Davids89** [comment]
Thank you! That was exactly what I wanted!
