### ISSUE TITLE
Containment Issues

### ISSUE THREAD

**Issue by zoesteinkamp** [codef0rmer/angular-dragdrop#252]
So I am having some difficulties with the containment option, its probably user error. But could you just help explain what im doing wrong with this?

data-drop="true" ng-model="list2"   jqyoui-droppable="{onDrop: 'onDrop', onOver:'onOver',multiple:true,containment:'offer'}" data-jqyoui-options

This code works fine up unit I added the containment with string, it throws this error.

Error: $fromEl[dropSettings.containment || 'offset'] is not a function. (In '$fromEl[dropSettings.containment || 'offset']()', '$fromEl[dropSettings.containment || 'offset']' is undefined)

So I assume it has to be named offset, then it stops throwing errors. But how the heck do I get the actual offset value? I have tried putting in my drop function, calling offset as a function, scope.offset. What is it supposed to be? Theres no examples of this being used in the demos.

 What im trying to do is get the location where a draggable is dropped. If im doing this wrong or theres a better way to solve this problem please let me know.

**Comment by codef0rmer** [comment]
Hey if you read the documentation carefully, the containment should be
either position or offset, not offer. Also do not get confused with
containment option in jqueryui.

**Comment by zoesteinkamp** [comment]
I see that, I know it has to be either position or offset, but shouldn't it return a variable? http://api.jquery.com/offset/ this is showing a top and left variable. How do i access these? What do i call?

**Comment by codef0rmer** [comment]
I am not sure what exactly you want to do. The code error you highlighted
before was because of $fromEl.offer() which is not a jqiery method.

**Comment by zoesteinkamp** [comment]
Well thats not the main issue, I just want to clarify that it needs to be offset/position in the string. What im wondering is that normally the jquery offset() call gives you a top and left variable, like this.
 
<script>
var p = $( "p:last" );
var offset = p.offset();
p.html( "left: " + offset.left + ", top: " + offset.top );
</script>

Which returns something like, 10 and 5, for offset.left and offset.right. Dosent this function if im reading the docs right do the same thing? I am trying to replicate these functions. 

  var $newPosX = ui.offset.left - $(this).offset().left;
   var $newPosY = ui.offset.top - $(this).offset().top;

But I can not use this, or at least it does not seem practical. And I have the ui.offset variables.  I thought that the offset function called on the droppable would give me the offset coordinates of the draggable.

**Comment by amitonkare** [comment]
Hey, I am also having an issue with containment. I thought it is the JqueryUI's containment option. Is it not that?
If not, how do I restrict the draggables to be dragged to drop area only. They should not be out of the drop area. Please help.

**Comment by zoesteinkamp** [comment]
Hey Amitonkare, you are looking for the data-jqyoui-options, containment option, found here http://api.jqueryui.com/draggable/#option-containment. Your code will look something like,

data-jqyoui-options="{ containment: 'div you want the draggable to be contained in'}" 

Im looking for the Jquery offset coordinates found here http://api.jquery.com/offset/, and hoping that codeformer can help me access these variables. Hope this answers your question thou!

**Comment by codef0rmer** [comment]
@zoesteinkamp: I think you want to get the offset value of the draggable which you can do with `onStart` method as:

```
$scope.onStart = function(event, ui) {
   console.log(ui.draggable.offset());
}
```
