### ISSUE TITLE
Resctrict droppable div to draggable items

### ISSUE THREAD

**Issue by Davids89** [codef0rmer/angular-dragdrop#253]
Is there any option to restricts the items I can drag to a droppable? For example, I have A and B types of items, and  two droppable containers, and I want A with 1, and B with 2. Is it possible? Any optional jquery code to make it? Thanks

**Comment by Davids89** [comment]
Ok, using jquery initialization and droppable accept I can determine wich items I can drop.

**Comment by Davids89** [comment]
Using that, I can't use the events in the droppable. I need to change the class of the draggable when It's not the appropiate for the droppable item :(. Any solution?

**Comment by turqayyilmaz** [comment]
have you been solved this problem?

**Comment by Davids89** [comment]
No, no yet

**Comment by codef0rmer** [comment]
It's fairly easy. Just mention the `accept` option in `jqyoui-options` on droppables.

http://api.jqueryui.com/droppable/#option-accept
