### ISSUE TITLE
data-drag doesn't to work after page load

### ISSUE THREAD

**Issue by pauldunn** [codef0rmer/angular-dragdrop#254]
When I set the data-drag attribute before page load it stops the div from being dragged.

If I dynamically add this attribute with a directive I can still drag the div.

Is this behaviour intended?

What I was hoping would happen is the directive could toggle if a div is draggable or not.

**Comment by codef0rmer** [comment]
Do you have a demo to share? What do you mean by "set the data-drag before page loads"

**Comment by pauldunn** [comment]
We can use your demo as an example:
http://codef0rmer.github.io/angular-dragdrop/#/ctrl

If you inspect one of the draggable elements and change the data-drag attribute to false I can still move the div.  According to your docs if the data-drag attribute is false then it should not be draggable.

What I am looking for is to be able to change this data-drag attribute dynamically and have the draggable div respond accordingly.

**Comment by codef0rmer** [comment]
I see. So that's not how it works. Even if you change the attribute to false from DevTools, Angular is unaware of the change. You have to use a model for `data-drag` as shown in the demo above. I would recommend to refer the code of the same demo.

**Comment by pauldunn** [comment]
ok even using a model it doesn't work.  If you look at the above demo and change the letters to gollum the drag updates to false but you can still drag the letters.

**Comment by codef0rmer** [comment]
That's because you've to update `drag` property to true against each of those items. Notice this dropCallback which checks if the arrange word is GOLLUM before disabling the drag behavior.

https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-ctrl-as-syntax.html#L58
