### ISSUE TITLE
Calling events jqyoui-droppable

### ISSUE THREAD

**Issue by Davids89** [codef0rmer/angular-dragdrop#256]
Hello, I'm working on a (I think) hard task. I have a draggable component, and when I dropped it, I convert it to a droppable element. My problem is, that I can not use the events (I have this component inside a droppable element) and I think is a problem between events. Can you help me please? Thanks

**Comment by codef0rmer** [comment]
@Davids89: It's difficult to provide a solution with limited information like this - a demo would be helpful. Also, if you need coding help, I would recommend using StackOverflow - Probably tag me if you want me to notice it.
