### ISSUE TITLE
Drag and drop does not work with dynamic added elements.

### ISSUE THREAD

**Issue by MiguelLattuada** [codef0rmer/angular-dragdrop#257]
I'm creating a directive that adds the `data-drag` and `jqyoui-draggable` attributes to an element on compile function, and they does not get the drag option.  Even manually adding the class attribute with `class="ui-draggable ui-draggable-handle"` does not work.

_Does the lib support something like this?_

I know events are added to existing elements, and can't handle new ones, but take a look at this: https://learn.jquery.com/events/event-delegation/

**Comment by codef0rmer** [comment]
Make sure you have included drag libraries correctly and compiling the element (with drag properties) properly. Adding those classes dynamically will not help.

If you share a demo on JSFiddle or Plnkr, it will be helpful for me to understand the problem well.
