### ISSUE TITLE
Dragged element index is not going back to previous value.

### ISSUE THREAD

**Issue by IOR88** [codef0rmer/angular-dragdrop#259]
Line 271 in angular-dragdrop.js file
zIndex = angular.element(jqyouiOptions.helper ? ui.helper : this).css('z-index');

Firstly i thought it is a wrong behaviour but right now I am not so sure.

Example, Dragged Element didn't have css z-index setted at all at beginning and after dragging, stop event added zIndex with value 2780 ? Actually I don't know from where this value came from,to check it i taked out div from all containers and situation was repeatable.

After some time i was wondering if maybe zIndex is taking from element to late, maybe index is added faster then 271 line is executed. 

After all i added default z-index on dragged element, and everything works fine.

Question is it necessary to add index on dragged element or it is a wrong behaviour of lib for elements withouth css z-index attr added ?

**Comment by codef0rmer** [comment]
Please provide working example on JSFiddle or Plnkr.
