### ISSUE TITLE
Prevent div positions from shifting after dropping an object somewhere else?

### ISSUE THREAD

**Issue by coolestcat** [codef0rmer/angular-dragdrop#260]
Hi! I am quite new to angular but I have been playing around for quite a while and can't seem to figure this out.

Currently, i have two divs, let's say (1) which is droppable, and another (2) that contains draggable imgs populated by ng-repeat from an array called field, which is also set as the ng-model. When I drag an img from (2) into (1), the img will appear in (1) as expected, but all the other imgs in (2) with an index after the img that I dragged will get shifted left.(more specifically, if i is the index of the image I dragged away, the img with index i+1 will move to where image i was, img i+2 will move to where img i+1 was, etc.). How do I prevent this? For example:

Right now, if I drag 4 , (2) will change like this:
(1 2 3 4 5 6) -> (1 2 3 5 6)

But instead, I want this to happen:

(1 2 3 4 5 6) -> (1 2 3  [space] 5 6)
(with a space where img 4 used to be).

Is there any way to do this? I hope the question is clear...

Thanks!

**Comment by codef0rmer** [comment]
Would you share a working demo?

**Comment by coolestcat** [comment]
http://embed.plnkr.co/zJzm4cVSnBTk5d7Iw7lU/

This is a simple illustration of what I mean. if you drag the second blue box from the pink area to the orange area, and THEN drag the first blue box from the orange area to the pink area, then the second blue box in the orange area will "snap back" to the top left corner (because the element in the array model has been spliced). Is there any way to avoid this?

**Comment by codef0rmer** [comment]
I see. One way to have a parent container for each draggable from the pink area with fixed width/height, so when a draggable is moved, the place will still be occupied because of it's container.
