### ISSUE TITLE
Update model on stop drag model.

### ISSUE THREAD

**Issue by mattletw** [codef0rmer/angular-dragdrop#265]
Hi people,

I have just a little question about some work which I can't get working. Is it possible to load from a model a list and alter the position after dragging an element around in the callback?

somehow I can't get it working.

**Comment by mattandrews** [comment]
Does the code here help? https://github.com/codef0rmer/angular-dragdrop/issues/216

**Comment by codef0rmer** [comment]
Reopen if the issue still persists.
