### ISSUE TITLE
Prevent duplicate items in droppable div

### ISSUE THREAD

**Issue by Davids89** [codef0rmer/angular-dragdrop#267]
Hello, is there an attribute to prevent duplicates items in the droppable model? I'm making it playing with the drop callbacks but I think I could be easier.

Thanks!

**Comment by codef0rmer** [comment]
@Davids89 A demo would be helpful.

**Comment by codef0rmer** [comment]
@Davids89 Accept takes a function where you could check if the item already exits or not.
http://api.jqueryui.com/droppable/#option-accept
