### ISSUE TITLE
Prevent dragging after successful drop

### ISSUE THREAD

**Issue by slclark** [codef0rmer/angular-dragdrop#268]
Is there a way to remove the drag ability after a successful drop?  I set data-drag to false after a successful drop, but the item still drags.

**Comment by codef0rmer** [comment]
@slclark you can simply update the attribute on the element using jQuery. You need a model for that such as `data-drag="{{isDraggable}}`. Whenever you wish to disable dragging, update `$scope.isDraggable = false`.
