### ISSUE TITLE
using ng-repeat inserts empty elements and removes items

### ISSUE THREAD

**Issue by yashhy** [codef0rmer/angular-dragdrop#270]
when using drag-drop along with ng-repeat between two arrays inserts empty objects in both the arrays see [this](https://plnkr.co/edit/t3lbEyQgdPeaCDytYZdU?p=preview) plunker

![Issue 1](http://i.stack.imgur.com/v5mRN.jpg)

When trying with n arrays along with ng-repeat one item from each array gets removed see [this](https://plnkr.co/edit/FQAGinXSImJ6YVrXqRBL?p=preview) plunker

![Issue 1](http://i.stack.imgur.com/V8fUE.jpg)

more info on [stackoverflow](http://stackoverflow.com/questions/36239187/angular-dragdrop-codef0rmer-ng-repeat-inserts-empty-object-and-removes-elements)

**Comment by codef0rmer** [comment]
I noticed that you have mentioned `ng-model="list1[$index]"` which means a separate model is used for each draggable. This makes it easy to drag it off and replaces a dragged item with `{}`.

I would recommend to take a look at following demo: https://github.com/codef0rmer/angular-dragdrop/blob/master/demo/dnd-lists.html
