### ISSUE TITLE
Demo site isn't working

### ISSUE THREAD

**Issue by fmpwizard** [codef0rmer/angular-dragdrop#271]
I click on the examples dropdown menu to select the more advanced examples but the page simply reloads

I see the url changes

http://codef0rmer.github.io/angular-dragdrop/#!/#%2F
http://codef0rmer.github.io/angular-dragdrop/#!/#%2Fconfirm

but the page is always the same.

Thanks

**Comment by RichardFans** [comment]
顶

**Comment by codef0rmer** [comment]
It seems that Angular1.x has made `html5mode` on by default.  Landed as https://github.com/codef0rmer/angular-dragdrop/commit/f603a44ef16b857cb23b68115b840b7b007d9209
