### ISSUE TITLE
Sortable Multiple Lists Example?

### ISSUE THREAD

**Issue by webstersprodigy** [codef0rmer/angular-dragdrop#273]
I am trying to implement something like the multiple list example (http://codef0rmer.github.io/angular-dragdrop/#!/list) but sortable. Right now I have two drop areas (one like in the multiple list example, one like in the sortable example), and things seem to get messed up when dragging between lists.

Is this scenario supported? Is there any way an example could be added with multiple sorted lists?

**Comment by averymd** [comment]
It might not be cool to mention another project here, but I struggled with this for a while and couldn't find a workable solution. I ended up switching to https://github.com/angular-ui/ui-sortable for this use case, and it worked very easily.

**Comment by codef0rmer** [comment]
@averymd No Problem. I myself recommended it though for sortable requirement :-)
