### ISSUE TITLE
Animation occurs from orginal not clone.

### ISSUE THREAD

**Issue by heck4** [codef0rmer/angular-dragdrop#276]
This is the code for my draggable:
```
<div data-drag="true" jqyoui-draggable="{animate:true, placeholder:'keep'}" ng-model="vm.list1"
        data-jqyoui-options="{helper: 'clone', appendTo: 'body', containment: '#shell-view', revert: 'invalid'}">
    <i class="fa fa-tag form-designer-field-icon" aria-hidden="true"></i><br />
    <div class="form-designer-field-title">
        <span>Label</span>
    </div>
</div>
```
This is the code for my droppable:
```
<div class="thumbnail" data-drop="true" data-jqyoui-options="{multiple:true}" ng-model="vm.list2" jqyoui-droppable>
</div>
```
I had to use the clone option, because the dragged element was appearing behind another div.  Plus the user is allowed to perform the same action multiple times.

When I drag the element into the droppable area, the animation occurs from the original element (located in a toolbox area) instead of moving the dragged element into position. The dragged element simply disappears while the animation from the original to the droppable area is occurring.

While this is a minor visual glitch, I would appreciate any help with making the animation cause the dragged item move into the dropped area.

Thanks,
Casey

**Comment by codef0rmer** [comment]
@heck4 add a demo pls?
