### ISSUE TITLE
How to reposition element on start dragging?

### ISSUE THREAD

**Issue by elarion** [codef0rmer/angular-dragdrop#278]
I have my draggable elements, these elements have a certain width and height and they are too big to be dropped in my droppable elements (I'm talking about UX).
So, to bypass this issue, when the draggable element is duplicate on dragging and have the  `ui-draggable-dragging`, I `display:none` certain parts to make it smaller and only keep the picture (which I reduce size).
To illustrate, my draggable elements contain a left container with text (which I hide) and a right container with the picture (which I keep).
The problem is that when a user start dragging the element from the left container the cursor will be outside of the right part because I hide this left side.

How to make the remaining right side have the cursor in the center on start dragging?
Is there a way to recenter the remaining picture?
May be I miss something here [http://api.jqueryui.com/draggable/](url)

Thank you.

**Comment by codef0rmer** [comment]
I'm not entirely sure of your problem unless you share a working demo but I think draggable helper may  solve the problem.

http://api.jqueryui.com/draggable/#option-helper

**Comment by elarion** [comment]
You mean that I should use a callback with the helper to return my dragged element ?

**Comment by codef0rmer** [comment]
Closing it assuming my answer may have solved the problem. Pls reopen with a demo only.
