### ISSUE TITLE
udpates of data-drag attribute of a draggable are not seen

### ISSUE THREAD

**Issue by mjcastillo** [codef0rmer/angular-dragdrop#280]
I have the data-drag attribute of my draggable items set to a property in my scope (data-drag="{{model.isDraggable(item)}}" data-jqyoui-options="{revert: false}" jqyoui-draggable="{animate:true}" question="item" ng-repeat="item in model.availableQuestions"). When the draggable first is initialized, the behavior properly follows whatever I set the scope property to (set to false, it won't  drag, set to true, it drags fine). However when I change the value of this property, the draggable does not see the change and doesn't changes it's behavior. I think the issue might be this line in the .js:

killWatcher = scope.$watch(function () { debugger; return scope.$eval(attrs.drag); }, updateDraggable);

But I am not familiar enough with how Angular watches work in the directive to fix it. I don't think the watch is working as expected.
Thank you,
Mike

**Comment by mjcastillo** [comment]
my bad. Was not using correctly. Sorry for the trouble

**Comment by thelamborghinistory** [comment]
May I ask what how you fixed it @mjcastillo ?
