### ISSUE TITLE
Demo doesn't work properly with bootstrap version 3.3.6

### ISSUE THREAD

**Issue by meenakshijha** [codef0rmer/angular-dragdrop#281]
Hi,

I am using the following version:

bootstrap 3.3.6
angular 1.4.3
jquery 1.11.4

Once I drag the items to the list box 1 or 2 , I am unable to place them back to the container/list they belonged to. Can you please help?

Thanks

**Comment by codef0rmer** [comment]
@meenakshijha without a demo it would be time consuming for me to reproduce the issue.

Can you add a demo in order to reopen it again?
