### ISSUE TITLE
How to change cursor style?

### ISSUE THREAD

**Issue by Jeevanandanj** [codef0rmer/angular-dragdrop#282]
I have tried like the following link, but the cursor is not changed.
https://jqueryui.com/draggable/#cursor-style

Please see the plunkr.
https://plnkr.co/edit/ZsxkiJzSJriNLebFkSi3?p=preview

I've added a property cursor:'move' in the draggable property.
But not effected while moving.

**Comment by codef0rmer** [comment]
@Jeevanandanj You can apply the jQueryUI specific configurations in `data-jqyoui-options="{revert: 'invalid',cursor:'move',cursorAt: { top: -5, left: -5 }}"` and remove the `cursor: pointer` in CSS on top.

**Updated Demo:** https://plnkr.co/edit/nflOl4mv33lJHfpYQfeP?p=preview
