### ISSUE TITLE
Cleanest way to disable drag and drop on mobile device

### ISSUE THREAD

**Issue by elarion** [codef0rmer/angular-dragdrop#284]
Hi, I would know how to fully disable drag and drop on mobile device, i use touchpunch.js but I only need it on tablet.
What I mean by "fully disable" is to not only disable item with drag or drop attribute but the whole component.
Any suggestions?

Thank you in advance.

**Comment by codef0rmer** [comment]
@elarion do not load jQuery, jQueryUI, and angular-dragdrop on Mobile.

**Comment by elarion** [comment]
Ok I though there was a method or something to disable it, and even if I don't like these alternatives it seems good. Thank you
