### ISSUE TITLE
Seems like the drag template is vulnerable for XSS attacks

### ISSUE THREAD

**Issue by benbracha** [codef0rmer/angular-dragdrop#285]
We create a drag item template which is based on user's input (e.g. item name).
Seems that this behaviour is vulnerable for XSS attack, in case the user put a script tag in the item name.
We can sanitize user's input, but as developers usually rely on Angular automatic sanitization process, we think that the data-jqyoui-options directive should take care of this as well, if possible.

For example, try to define this draggable item:
```
<div
   data-drag="true"
   jqyoui-draggable
   data-jqyoui-options="{helper: getItemDragTemplate(), appendTo: 'body'}">
```

Where the getItemDragTemlpate is:
```
<div>item.name</div>
```
Where item.name is some user malicious input, for example:
```
<script>alert('hello')</script>
```

Dragging such an item will cause the script to run.

**Comment by codef0rmer** [comment]
The jQueryUI helper property usually takes an HTML or a DOM, so if you are asking users for values, you should escape it. It's nothing to do with Angular or angular-dragdrop.

**Comment by benbracha** [comment]
I know. Just suggesting as the jqyouiDraggable directive is aware of the data-jqyoui-options, and binds them to the element, maybe it can sanitze them by itself. As I said, angularJS developers are usually not aware for such issues as they are automatically handled, and I would expect any angular based directive to do that, thus making the angular ecosystem more secure.

**Comment by codef0rmer** [comment]
Not really, `getItemDragTemplate` method is a part of your controller so I do not want to bloat angular-dragdrop codebase for all having it. I would recommend you to take care of that as it's application specific requirement.

**Comment by benbracha** [comment]
I don't think that having angular elements to validate against potential XSS is an application specific issue.
Looking at angular-dragdrop and jqueryUI draggable code, I think there is an option to make angular-dragdrop more secure IMHO.
As the "helper" option of jqueryUI draggable may be a function that should return a DOM element, we can make sure it is well sanitized when providing the helper function result to jqueryUI.

Something like the following can be done (or maybe an optional configuration for angular-dragdrop):

if (typeof jqyouiOptions.helper === 'function') {
              var originHelper = jqyouiOptions.helper;
              jqyouiOptions.helper = function() {
                return $sanitize(originHelper());
              };
            }


Not sure this is the best solution.. 
Anyway, we will for sure do sanitization ourselves, but I would consider such option to be as part of the angular-dragdrop directive.

**Comment by codef0rmer** [comment]
@benbracha I really appreciate your efforts in providing the solution. However, not everybody allows to modify the markup before dragging/dropping unlike your requirement. That's why I did not want to add the fix in angular-dragdrop. I hope it clarifies the issue.

**Comment by benbracha** [comment]
I'm not sure I follow.. because jqueryUI draggable, which you use, allows to change the markup.
This is done by providing a function through an "helper" property:
https://api.jqueryui.com/draggable/#option-helper

All I'm saying is that, if helper is a function - it must return a DOM element, which means it should be sanitized (or at least optional sanitized..).
