### ISSUE TITLE
sortable animation before dropping the item

### ISSUE THREAD

**Issue by nianiaJR** [codef0rmer/angular-dragdrop#289]
Thx, I have a problem with your sortable example: http://codef0rmer.github.io/angular-dragdrop/#!/sortable. 

I want to see the sortable reorder animation when I drag the item on other items. It's just like the reorder when I drop the item finally. Could I set any options to make it ? Such as the jqueryui sortable demo here: http://api.jqueryui.com/sortable/

**Comment by codef0rmer** [comment]
@nianiaJR Yeah, Unfortunately there is no way to integrate Sortable in angular-dragdrop. I think if you go ahead with creating your own, might be complex but give it a shot if you want.

**Comment by nianiaJR** [comment]
Thank you prompt reply
