### ISSUE TITLE
some errors 

### ISSUE THREAD

**Issue by eniniz** [codef0rmer/angular-dragdrop#297]
I copy past the example of codepen, but I get those errors: 

1. angular-dragdrop.js:414 Uncaught TypeError: Cannot read property 'fn' of undefined
2. angular.js:13920 TypeError: $ is not a function
    at new <anonymous> (file:///D:/Nouveau%20dossier%20(2)/angular-dragdrop.js:37:5)
    at Object.instantiate (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:42:56)
    at Object.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.8/angular.min.js:42:352
    ......

**Comment by Lywangwenbin** [comment]
me too,  when the page load, there exists 'Cannot read property 'fn' of undefined', maybe because the jQuery load to slow to run

**Comment by mangiavellano** [comment]
@eniniz @Lywangwenbin It's because you haven't loaded `jQuery` before `angular-dragdrop`, the package needs jQuery to run.

```
import 'jquery';
import 'angular-dragdrop';
```

Hope that helps.

**Comment by w0ns88** [comment]
I have the same issue, I made sure `jquery` and `jquery-ui` are loaded before `angular` and `angular-dragdrop` still get the error:

> Uncaught TypeError: Cannot read property 'fn' of undefined

This comes from this `angular-dragdrop` code (line 414):
 
```
$.fn.ngattr = function(name, value) {
    var element = this[0];

    return element.getAttribute(name) || element.getAttribute('data-' + name);
  }; 
```
any ideas?

**Comment by codef0rmer** [comment]
Make sure you have loaded jQuery with `window.jQuery`.
