### ISSUE TITLE
snapTolerance not working

### ISSUE THREAD

**Issue by jaysongyn** [codef0rmer/angular-dragdrop#312]
I'm trying to use snapTolerance but is not working:

  data-jqyoui-options="{revert: 'invalid',snapTolerance:'10'}"

**Comment by codef0rmer** [comment]
@jaysongyn Have a working demo to look at? Make sure to set `snap: true` as well.

Refer, http://api.jqueryui.com/draggable/#option-snapTolerance

**Comment by jaysongyn** [comment]
@codef0rmer Thank you for your quick reply.

I tried to use the demo and add  data-jqyoui-options="{snap: true,snapTolerance: 10}"

https://plnkr.co/edit/3sHBOcZzXdLadrrdK6pJ?p=preview

**Comment by codef0rmer** [comment]
@jaysongyn I'm not sure what snap or snapTolerance must do. Can you create the jqueryUI demo to check if it works there? 

http://jqueryui.com/draggable/#snap-to

**Comment by jaysongyn** [comment]
@codef0rmer thank for your support. I was doing wrong, to use snapTolerance I must have two draggable objects. I was trying to use snapTolerance when I drop my draggabable object to drop area.

**Comment by codef0rmer** [comment]
Cool.
