### ISSUE TITLE
Having problems implemeting visual feedback on droppable area

### ISSUE THREAD

**Issue by rodrigovallades** [codef0rmer/angular-dragdrop#317]
Hi!

The documentation says that **data-jqyoui-options** object should hold all the valid options supported by **jQueryUI Droppable**.

I'm having a hard time using the droppable "classes" attribute, as described in http://jqueryui.com/droppable/#visual-feedback.

I tried something like this:

`<div data-drop="true" data-jqyoui-options="classes: { 'ui-droppable-active': 'ui-state-default'}" jqyoui-droppable>`

But I'm getting a syntax error:

> `Error: [$parse:syntax] Syntax Error: Token ':' is an unexpected token at column 8 of the expression [classes: { 'ui-droppable-active': 'ui-state-default'}] starting at [: { 'ui-droppable-active': 'ui-state-default'}].`

What I'm trying to achieve is visual feedback on the droppable area as soon as I start dragging an element.

Any help?

**Comment by rodrigovallades** [comment]
Thank you, I was missing the extra brackets.

But even then, I'm not getting the expected result. The systax error is gone, though.

I'll keep trying.

**Comment by codef0rmer** [comment]
@rodrigovallades Yeah, never stop trying 👍

**Comment by jambway** [comment]
$scope.optionsList1 = {
    activeClass: 'ui-state-hover',
    hoverClass: 'ui-state-active',
  };
