### ISSUE TITLE
Center Draggable element in DropZone

### ISSUE THREAD

**Issue by w0ns88** [codef0rmer/angular-dragdrop#319]
Hi,
I'm new to this, I really like your directive, it works really well.
I just have an issue when dropping the draggable element in the droppable area. It does not recenter itself (or automatically move to the center of the drop element- or desired position) and I cannot find the solution to do so. Some guidance on what to do would be much appreciated!
Thanks!

**Comment by codef0rmer** [comment]
@w0ns88 Pls share a demo to investigate further.

**Comment by w0ns88** [comment]
@codef0rmer I have just found out about `snap`, `snapMode` and `snapTolerance`.
I have added the following to my draggable element: 
`data-jqyoui-options="{revert: 'invalid', snap:'.drop-container', snapMode: 'inner', snapTolerance: 33}"` where the `.drop-container` is the class of my droppable element. It works just as I needed.
Thanks :) issue can be closed.
