### ISSUE TITLE
dragdrop doesn't play nicely with jQuery UI's sortable

### ISSUE THREAD

**Issue by raleighvon** [codef0rmer/angular-dragdrop#37]
Hi,

Firstly thank you for writing this drag drop directive. I have two columns, one is draggable, the other droppable. The droppable column is also sortable using jQuery UI but when trying to sort, a droppable event is triggered and this droppable event expects a dragged item but we weren't dragging we were sorting and so "dragModel" is undefined which causes an error and then sorting never happens.

Adding:

``` javascript
   if (!dragModel) return;
```

to line 64 seems to fix the problem.

Thanks

**Comment by fkotsian** [comment]
Hey everyone,

 If you don't need any of the jqyoui-draggable options, you can sort items between two lists and their corresponding ng-models by tweaking some of the settings:

- Add ui-sortable to the containing element (as in fiddle http://jsfiddle.net/codef0rmer/ey87K/4/ above)
- Add connectWith option to the ui-sortable element, referencing the elements you want to sort between (e.g. ui-sortable="{connectWith: '.caption'}")
- Remove jqyoui-draggable from your draggable element

I imagine this removes the draggable callbacks that were conflicting with the sortable callbacks. Works alright for me - will see if I run into any problems down the line

**Comment by seaBubble** [comment]
Hi everyone,

I also have this problem. It has been quite a while since the last comment here...is there a fix or a workaround anyone could share?

Thanks!
