### ISSUE TITLE
Drop-callback not called on minified version

### ISSUE THREAD

**Issue by tapioko** [codef0rmer/angular-dragdrop#81]
Drop-callback not called on minified version because dropSettings can not be found from the element.

Minified version has this code. In the last line "this" should be replaced with r (which is the element). Otherwise s (dropSettings) is not properly populated.

.directive("jqyouiDroppable", ["ngDragDropService", function(e) {
  return {restrict:"A", priority:1, link: function(n,r,i) {
    var s;
    var o = function(o,u){
      if(o){
        s = n.$eval(t.element(this).attr("jqyoui-droppable") || t.element(thi).attr("data-jqyoui-droppable")) || {};

**Comment by michnath** [comment]
I got the same issue on the minified version. Could anybody tell me the workaround? :(
I have included the dependency on the right order: ['jquery', 'jqueryUi', 'angular']

**Comment by codef0rmer** [comment]
@michnath: Can you share more details?

**Comment by michnath** [comment]
hi @codef0rmer 
Here is the exception raised:
TypeError: undefined is not a function
    at Object.angular.module.service.directive.directive.link.updateDroppable [as fn] (main-built.js:13418)
    at k.$get.k.$digest (main-built.js:533)
    at k.$get.k.$apply (main-built.js:536)
    at l (main-built.js:492)
    at u (main-built.js:497)
    at XMLHttpRequest.E.onreadystatechange (main-built.js:498)

main-built.js:13418 is pointing to the bolded line:
}]).directive('jqyouiDroppable', ['ngDragDropService', function(ngDragDropService) {
    return {
      restrict: 'A',
      priority: 1,
      link: function(scope, element, attrs) {
        var dropSettings;
        var updateDroppable = function(newValue, oldValue) {
          if (newValue) {
            dropSettings = scope.$eval(angular.element(element).attr('jqyoui-droppable') || angular.element(element).attr('data-jqyoui-droppable')) || {};
            element
             ** .droppable({disabled: false})**

**Comment by codef0rmer** [comment]
@michnath: That mainly happens when the order of dependencies is not correct. Make sure this `['jquery', 'jqueryUi', 'angular']` actually injects JavaScript files in a correct order.
