### ISSUE TITLE
Dragging inside a div with overflow:auto or scroll clips the dragged item.

### ISSUE THREAD

**Issue by rcfrias** [codef0rmer/angular-dragdrop#86]
If we have a scrollable list of "draggable" elements, we will find out that if we drag to a side, the dragged content clips (disappears) while we are not on its container.

appendTo:"body"  fails when added to data-jqyoui-options

Is this a bug? or it does have a quick-fix?

Container has a overflow setting, and just "visible" shows the content to a side but eliminates the vertical scrollbar.

**Comment by jatinseth2007** [comment]
To use it with 'overflow: scroll' solve this issue, we need to use helper: 'clone' with scroll: false option then only it will work
