### ISSUE TITLE
Having huge lib as jQuery UI in requirements just for drag'n'drop feature?

### ISSUE THREAD

**Issue by MechanisM** [codef0rmer/angular-dragdrop#90]
I know a few small libs which are focused on drag'n'drop functionality and doesn't have jquery ui in requirements. Maybe better to use some small libs for it?

**Comment by Avcajaraville** [comment]
I think this should be reflected more clearly on the documentation.

I agree with MechanisM, btw.

**Comment by codef0rmer** [comment]
@Avcajaraville : already mentioned in the README
