### ISSUE TITLE
Using the same model for drag and drop only allows for swapping, not repositioning, of items

### ISSUE THREAD

**Issue by peteclodi** [codef0rmer/angular-dragdrop#92]
The current implementation will only allow for the swapping of items when the drop target and the drag target point to the same model. It would be useful to be able to use the drag and drop functionality to allow for the repositioning of an item within the model.

So instead of the dnd-ctrl-as-syntax.html example swapping the 2 letters, the dragged and the dropped. It would place the dropped letter in between the dropped letter and the one preceding it.
Swap:
![swap](https://cloud.githubusercontent.com/assets/5898507/2571727/c9354adc-b909-11e3-8d80-d08752ba14e5.png)
 Insert:
![insert](https://cloud.githubusercontent.com/assets/5898507/2571733/da98d276-b909-11e3-9b6d-bee2016e25a4.png)

**Comment by kashban** [comment]
I'm working on the exact same functionality too in a customer's app. Right now I do it manually by inserting the dragged item at the location before the dropped on one and removing it from it's former position, but having this out of the box would be a nice addition.
